// 机场数据库
const AIRPORTS_DATA = [
  {
    "id": "yuntu",
    "name": "云图机场",
    "nameEn": "Yuntu",
    "icon": "YT",
    "tier": "高端",
    "rating": 5,
    "price": {
      "monthly": 25,
      "quarterly": 75,
      "yearly": 300
    },
    "traffic": "150GB/月起",
    "devices": 10,
    "protocols": [
      "Shadowsocks",
      "V2Ray",
      "Trojan"
    ],
    "features": [
      "金融级专线",
      "Netflix/ChatGPT解锁",
      "1倍率无陷阱",
      "TikTok原生"
    ],
    "tags": [
      "金融级专线",
      "流媒体",
      "ChatGPT"
    ],
    "status": "正常运营",
    "description": "金融级专线，新上线优质机场",
    "affUrl": "https://vip.ytjcok.org/#/register?code=iV8ahCNE",
    "promoCode": "yt88",
    "reviewUrl": "airport-review.html?id=yuntu",
    "avgSpeed": 928,
    "avgLatency": 7.4,
    "stability": 99.8
  },
  {
    "id": "kunpeng",
    "name": "鲲鹏加速",
    "nameEn": "KunPeng",
    "icon": "KP",
    "tier": "入门",
    "rating": 4.2,
    "price": { "monthly": 1, "quarterly": 12, "yearly": 88 },
    "traffic": "1GB 起（月付 12 元 99GB）",
    "devices": 5,
    "protocols": ["Shadowsocks", "V2Ray"],
    "features": ["1 元试用 1GB", "1.0 倍率无陷阱", "Netflix/ChatGPT 解锁", "4K 视频流畅"],
    "tags": ["1元试用", "低价入门", "流媒体", "ChatGPT"],
    "status": "正常运营",
    "description": "以 1 元试用为特点的入门机场，1GB 全速专线流量，支持 ChatGPT、Netflix、TikTok 解锁，1.0 倍率不玩文字游戏，试用满意后可升级 12 元/99GB 主力套餐。",
    "affUrl": "https://kunpengjiasu.com/#/register?code=tQvtkYsB",
    "promoCode": null,
    "reviewUrl": "airport-review.html?id=kunpeng",
    "avgSpeed": 500,
    "avgLatency": 35,
    "stability": 97.0
  },
  {
    "id": "jisuyun",
    "name": "极速Cloud",
    "nameEn": "JisuCloud",
    "icon": "JC",
    "tier": "高端",
    "rating": 4.9,
    "price": {
      "monthly": 30,
      "quarterly": 85,
      "yearly": 320
    },
    "traffic": "200GB/月起",
    "devices": 8,
    "protocols": [
      "VLess",
      "V2Ray",
      "Trojan"
    ],
    "features": [
      "CN2GIA三网精品",
      "TikTok原生IP",
      "28+地区节点",
      "VLess协议"
    ],
    "tags": [
      "CN2GIA",
      "TikTok",
      "流媒体"
    ],
    "status": "正常运营",
    "description": "三网CN2GIA精品线路，TikTok原生",
    "affUrl": "https://ygbk.jsjc456789.com/#/register?code=EocII8EW",
    "promoCode": null,
    "reviewUrl": "airport-review.html?id=jisuyun",
    "avgSpeed": 906,
    "avgLatency": 27,
    "stability": 99.5
  },
  {
    "id": "shunyun",
    "name": "瞬云",
    "nameEn": "ShunYun",
    "icon": "SY",
    "tier": "中端",
    "rating": 4.4,
    "price": {
      "monthly": 16,
      "quarterly": 45,
      "yearly": 168
    },
    "traffic": "100GB/月起",
    "devices": 6,
    "protocols": [
      "Shadowsocks",
      "V2Ray"
    ],
    "features": [
      "IEPL专线",
      "Netflix解锁",
      "套餐灵活",
      "年付实惠"
    ],
    "tags": [
      "IEPL",
      "性价比",
      "流媒体"
    ],
    "status": "正常运营",
    "description": "IEPL专线，套餐灵活性价比高",
    "affUrl": "https://ccc.jichang.best/#/register?code=MhKYAnsG",
    "promoCode": "20off",
    "reviewUrl": "airport-review.html?id=shunyun",
    "avgSpeed": 706,
    "avgLatency": 34,
    "stability": 99.2
  },
  {
    "id": "huanyuyun",
    "name": "寰宇云",
    "nameEn": "HuanYuYun",
    "icon": "HY",
    "tier": "中端",
    "rating": 4.6,
    "price": {
      "monthly": 14,
      "quarterly": 39,
      "yearly": 148
    },
    "traffic": "120GB/月起",
    "devices": 6,
    "protocols": [
      "Shadowsocks",
      "V2Ray",
      "Trojan"
    ],
    "features": [
      "IPLC专线",
      "不限时流量",
      "Netflix解锁",
      "三网优化"
    ],
    "tags": [
      "IPLC",
      "性价比",
      "流媒体"
    ],
    "status": "正常运营",
    "description": "IPLC专线，不限时流量套餐",
    "affUrl": "https://hyy.52kok.cn/#/register?code=CPBmzXgk",
    "promoCode": "KY78",
    "reviewUrl": "airport-review.html?id=huanyuyun",
    "avgSpeed": 706,
    "avgLatency": 14,
    "stability": 99.7
  },
  {
    "id": "jilianyun",
    "name": "极连云",
    "nameEn": "JiLianYun",
    "icon": "JL",
    "tier": "中端",
    "rating": 4.6,
    "price": {
      "monthly": 18,
      "quarterly": 50,
      "yearly": 188
    },
    "traffic": "150GB/月起",
    "devices": 8,
    "protocols": [
      "Shadowsocks",
      "V2Ray",
      "Trojan"
    ],
    "features": [
      "全IPLC专线",
      "原生IP",
      "流媒体解锁",
      "ChatGPT可用"
    ],
    "tags": [
      "IPLC",
      "原生IP",
      "ChatGPT"
    ],
    "status": "正常运营",
    "description": "全IPLC专线，原生IP解锁流媒体",
    "affUrl": "https://haozevpn.jlyvipaff.com/#/?code=KUKfOY13",
    "promoCode": null,
    "reviewUrl": "airport-review.html?id=jilianyun",
    "avgSpeed": 606,
    "avgLatency": 19.6,
    "stability": 99.5
  },
  {
    "id": "dageyun",
    "name": "大哥云",
    "nameEn": "DaGeYun",
    "icon": "DG",
    "tier": "入门",
    "rating": 4.7,
    "price": {
      "monthly": 19,
      "quarterly": 53,
      "yearly": 198
    },
    "traffic": "100GB/月起",
    "devices": 5,
    "protocols": [
      "Shadowsocks",
      "V2Ray"
    ],
    "features": [
      "老牌稳定",
      "免费试用",
      "Netflix解锁",
      "ChatGPT可用"
    ],
    "tags": [
      "性价比",
      "新手友好",
      "流媒体"
    ],
    "status": "正常运营",
    "description": "老牌稳定机场，免费试用支持",
    "affUrl": "https://aff02.dgy02.com/#/register?code=PQdpFA0R",
    "promoCode": "dgy",
    "reviewUrl": "airport-review.html?id=dageyun",
    "avgSpeed": 506,
    "avgLatency": 21.6,
    "stability": 99.6
  },
  {
    "id": "guangsuyun",
    "name": "光速云",
    "nameEn": "GuangSuYun",
    "icon": "GS",
    "tier": "中端",
    "rating": 4.8,
    "price": {
      "monthly": 23,
      "quarterly": 65,
      "yearly": 240
    },
    "traffic": "148GB/月起",
    "devices": 999,
    "protocols": [
      "Shadowsocks",
      "V2Ray",
      "Trojan"
    ],
    "features": [
      "全球IPLC专线",
      "单节点2.5Gbps",
      "流媒体解锁",
      "ChatGPT可用"
    ],
    "tags": [
      "IPLC专线",
      "流媒体",
      "ChatGPT"
    ],
    "status": "正常运营",
    "description": "全球IPLC专线，单节点2.5Gbps高速带宽",
    "affUrl": "https://sjds8ds.guangsut.sbs/#/?code=XrQ58TLd",
    "promoCode": null,
    "reviewUrl": "airport-review.html?id=guangsuyun",
    "avgSpeed": 719.8,
    "avgLatency": 22,
    "stability": 99.3
  },
  {
    "id": "jindouyun",
    "name": "筋斗云",
    "nameEn": "JinDouYun",
    "icon": "JD",
    "tier": "中端",
    "rating": 4.5,
    "price": {
      "monthly": 16,
      "quarterly": 45,
      "yearly": 168
    },
    "traffic": "120GB/月起",
    "devices": 6,
    "protocols": [
      "Shadowsocks",
      "V2Ray",
      "Trojan"
    ],
    "features": [
      "IEPL专线",
      "三网优化",
      "Netflix解锁",
      "ChatGPT可用"
    ],
    "tags": [
      "IEPL",
      "三网优化",
      "ChatGPT"
    ],
    "status": "正常运营",
    "description": "IEPL专线，三网优化稳定",
    "affUrl": "https://jdy.52kok.cn/#/register?code=wUKiwosG",
    "promoCode": null,
    "reviewUrl": "airport-review.html?id=jindouyun",
    "avgSpeed": 606,
    "avgLatency": 21.6,
    "stability": 99.4
  },

  {
    "id": "sujie",
    "name": "速界",
    "nameEn": "Sujie",
    "icon": "SJ",
    "tier": "入门",
    "rating": 4.1,
    "price": { "monthly": 6, "quarterly": 16, "yearly": 58 },
    "traffic": "100GB/月起",
    "devices": 5,
    "protocols": ["IEPL", "V2Ray"],
    "features": ["真IEPL专线", "低价套餐", "适合轻度使用"],
    "tags": ["IEPL", "性价比", "入门"],
    "status": "待核实AFF",
    "description": "低价 IEPL 线路机场，适合先用月付套餐测试。",
    "affUrl": "https://momlise.szjtfp.xyz/#/?code=GPjugEyt",
    "promoCode": null,
    "reviewUrl": "airport-review.html?id=sujie",
    "avgSpeed": 700,
    "avgLatency": 25,
    "stability": 98.5
  },
  {
    "id": "naxi",
    "name": "奶昔机场",
    "nameEn": "Nexitally",
    "icon": "NX",
    "tier": "高端",
    "rating": 4.8,
    "price": { "monthly": 89, "quarterly": 249, "yearly": 899 },
    "traffic": "500GB/月起",
    "devices": 10,
    "protocols": ["IEPL", "Trojan", "V2Ray"],
    "features": ["顶级IEPL专线", "大流量套餐", "多地区节点"],
    "tags": ["IEPL", "大流量", "高端"],
    "status": "待核实AFF",
    "description": "高端 IEPL 专线机场，适合对带宽和稳定性有较高要求的用户。",
    "affUrl": "https://nxonearth.com/signupbyemail.aspx?MemberCode=0fdc762d5c714053b042de02a8cdf10220251207224255",
    "promoCode": null,
    "reviewUrl": "airport-review.html?id=naxi",
    "avgSpeed": 1000,
    "avgLatency": 18,
    "stability": 99.7
  },
  {
    "id": "baoyun",
    "name": "宝云",
    "nameEn": "Baoyun",
    "icon": "BY",
    "tier": "入门",
    "rating": 3.8,
    "price": { "monthly": 4, "quarterly": 11, "yearly": 39 },
    "traffic": "100GB/月起",
    "devices": 3,
    "protocols": ["VLESS", "V2Ray"],
    "features": ["海外中转", "低价入门", "轻度访问"],
    "tags": ["VLESS", "海外中转", "低价"],
    "status": "待核实AFF",
    "description": "低价海外中转线路，适合轻度访问和临时备用。",
    "affUrl": "https://888by.baoyundl.com/#/register?code=089ta958",
    "promoCode": null,
    "reviewUrl": "airport-review.html?id=baoyun",
    "avgSpeed": 280,
    "avgLatency": 46,
    "stability": 96.5
  },
  {
    "id": "wgetcloud",
    "name": "WgetCloud",
    "nameEn": "WgetCloud",
    "icon": "WG",
    "tier": "高端",
    "rating": 4.7,
    "price": { "monthly": 39, "quarterly": 109, "yearly": 399 },
    "traffic": "200GB/月起",
    "devices": 8,
    "protocols": ["专线", "Shadowsocks", "Trojan"],
    "features": ["AWS专线加速", "全球节点", "多平台支持"],
    "tags": ["AWS", "专线", "全球节点"],
    "status": "待核实AFF",
    "description": "采用 AWS 专线加速的高端服务，适合重视覆盖和稳定性的用户。",
    "affUrl": "https://invite.wgetcloud.ltd/auth/register?code=pQAnrf",
    "promoCode": null,
    "reviewUrl": "airport-review.html?id=wgetcloud",
    "avgSpeed": 900,
    "avgLatency": 24,
    "stability": 99.4
  },
  {
    "id": "feiniao",
    "name": "飞鸟机场",
    "nameEn": "Feiniao",
    "icon": "FN",
    "tier": "中端",
    "rating": 4.6,
    "price": { "monthly": 25, "quarterly": 68, "yearly": 238 },
    "traffic": "150GB/月起",
    "devices": 8,
    "protocols": ["IEPL", "V2Ray", "Trojan"],
    "features": ["IEPL国际专线", "多地区覆盖", "流媒体支持"],
    "tags": ["IEPL", "国际专线", "流媒体"],
    "status": "待核实AFF",
    "description": "IEPL 国际专线机场，适合日常访问和流媒体使用。",
    "affUrl": "https://vip.ytjcok.org/#/register?code=iV8ahCNE",
    "promoCode": null,
    "reviewUrl": "airport-review.html?id=feiniao",
    "avgSpeed": 850,
    "avgLatency": 20,
    "stability": 99.1
  },
  {
    "id": "glados",
    "name": "GlaDOS",
    "nameEn": "GlaDOS",
    "icon": "GD",
    "tier": "中端",
    "rating": 4.5,
    "price": { "monthly": 15, "quarterly": 42, "yearly": 150 },
    "traffic": "200GB/月起",
    "devices": 6,
    "protocols": ["BGP", "V2Ray", "Trojan"],
    "features": ["BGP中转", "部分专线", "流媒体支持"],
    "tags": ["BGP", "中转", "流媒体"],
    "status": "待核实AFF",
    "description": "BGP 中转与专线混合线路，适合日常多平台使用。",
    "affUrl": "",
    "promoCode": null,
    "reviewUrl": "airport-review.html?id=glados",
    "avgSpeed": 600,
    "avgLatency": 28,
    "stability": 98.9
  },
  {
    "id": "jiuyun",
    "name": "九云",
    "nameEn": "Jiuyun",
    "icon": "JY",
    "tier": "入门",
    "rating": 4.2,
    "price": { "monthly": 6, "quarterly": 18, "yearly": 68 },
    "traffic": "150GB/月起",
    "devices": 5,
    "protocols": ["VLESS", "V2Ray"],
    "features": ["VLESS海外中转", "低价套餐", "ChatGPT支持", "流媒体解锁"],
    "tags": ["VLESS", "海外中转", "低价"],
    "status": "正常运营",
    "description": "主打低价海外中转线路，适合预算有限和轻度使用。",
    "affUrl": "https://888.jiuyundl.com/#/register?code=SDsIO7kq",
    "promoCode": null,
    "reviewUrl": "airport-review.html?id=jiuyun",
    "avgSpeed": 650,
    "avgLatency": 35,
    "stability": 98.5
  },
  {
    "id": "tag",
    "name": "TAG机场",
    "nameEn": "TAG",
    "icon": "TG",
    "tier": "高端",
    "rating": 4.3,
    "price": { "monthly": 20, "quarterly": 56, "yearly": 200 },
    "traffic": "100GB/月起",
    "devices": 6,
    "protocols": ["IP", "BGP", "Trojan"],
    "features": ["家宽原生IP", "BGP优化", "流媒体支持"],
    "tags": ["原生IP", "BGP", "家宽"],
    "status": "待核实AFF",
    "description": "提供家宽原生 IP 与 BGP 优化线路，适合需要原生网络环境的用户。",
    "affUrl": "",
    "promoCode": null,
    "reviewUrl": "airport-review.html?id=tag",
    "avgSpeed": 500,
    "avgLatency": 30,
    "stability": 98.6
  },
  {
    "id": "chaoyue",
    "name": "超悦机场",
    "nameEn": "Chaoyue",
    "icon": "CY",
    "tier": "入门",
    "rating": 3.6,
    "price": { "monthly": 6.8, "quarterly": 18, "yearly": 68 },
    "traffic": "100GB/月起",
    "devices": 4,
    "protocols": ["Hysteria2", "V2Ray"],
    "features": ["Hysteria2中转", "低价套餐", "轻度使用"],
    "tags": ["Hysteria2", "中转", "低价"],
    "status": "待核实AFF",
    "description": "Hysteria2 中转线路，主打低价和基础访问需求。",
    "affUrl": "",
    "promoCode": null,
    "reviewUrl": "airport-review.html?id=chaoyue",
    "avgSpeed": 200,
    "avgLatency": 52,
    "stability": 95.8
  },
  {
    "id": "yiyuan",
    "name": "一元机场",
    "nameEn": "Yiyuan",
    "icon": "1Y",
    "tier": "入门",
    "rating": 3.2,
    "price": { "monthly": 1, "quarterly": 3, "yearly": 10 },
    "traffic": "30GB/月起",
    "devices": 2,
    "protocols": ["V2Ray", "Shadowsocks"],
    "features": ["超低价格", "普通中转", "适合备用"],
    "tags": ["低价", "中转", "备用"],
    "status": "待核实AFF",
    "description": "超低价普通中转服务，更适合作为备用线路。",
    "affUrl": "",
    "promoCode": null,
    "reviewUrl": "airport-review.html?id=yiyuan",
    "avgSpeed": 45,
    "avgLatency": 68,
    "stability": 93.5
  },
  {
    "id": "miaomiao",
    "name": "秒秒云",
    "nameEn": "Miaomiao",
    "icon": "MM",
    "tier": "入门",
    "rating": 3.7,
    "price": { "monthly": 14, "quarterly": 39, "yearly": 140 },
    "traffic": "100GB/月起",
    "devices": 4,
    "protocols": ["VLESS", "V2Ray"],
    "features": ["海外中转", "多地区节点", "轻度流媒体"],
    "tags": ["VLESS", "海外中转", "性价比"],
    "status": "待核实AFF",
    "description": "VLESS 海外中转线路，适合日常访问和备用使用。",
    "affUrl": "https://m2.mouhiojl.com:8888/#/register?code=6u2dHtD4",
    "promoCode": null,
    "reviewUrl": "airport-review.html?id=miaomiao",
    "avgSpeed": 300,
    "avgLatency": 48,
    "stability": 96.5
  },
  {
    "id": "shanshui",
    "name": "山水云",
    "nameEn": "Shanshui",
    "icon": "SS",
    "tier": "入门",
    "rating": 3.8,
    "price": { "monthly": 15, "quarterly": 42, "yearly": 150 },
    "traffic": "100GB/月起",
    "devices": 5,
    "protocols": ["V2Ray", "Shadowsocks"],
    "features": ["优质中转", "多平台支持", "日常访问"],
    "tags": ["中转", "性价比", "日常"],
    "status": "待核实AFF",
    "description": "优质中转线路，适合日常访问和轻度使用。",
    "affUrl": "https://sldm1.ssyylf.com/#/register?code=4WTXbMwy",
    "promoCode": null,
    "reviewUrl": "airport-review.html?id=shanshui",
    "avgSpeed": 320,
    "avgLatency": 42,
    "stability": 96.8
  },
  {
    "id": "jinyun",
    "name": "锦云",
    "nameEn": "Jinyun",
    "icon": "JY",
    "tier": "入门",
    "rating": 3.5,
    "price": { "monthly": 6, "quarterly": 16, "yearly": 58 },
    "traffic": "80GB/月起",
    "devices": 4,
    "protocols": ["V2Ray", "Shadowsocks"],
    "features": ["海外中转", "低价入门", "基础线路"],
    "tags": ["海外中转", "低价", "入门"],
    "status": "待核实AFF",
    "description": "低价海外中转服务，适合入门和备用场景。",
    "affUrl": "https://jybdw1.wanhlj.com:8888/#/register?code=0xeLRRWB",
    "promoCode": null,
    "reviewUrl": "airport-review.html?id=jinyun",
    "avgSpeed": 260,
    "avgLatency": 50,
    "stability": 95.7
  },
  {
    "id": "liyun",
    "name": "鲤云",
    "nameEn": "Liyun",
    "icon": "LY",
    "tier": "入门",
    "rating": 3.6,
    "price": { "monthly": 7, "quarterly": 19, "yearly": 68 },
    "traffic": "100GB/月起",
    "devices": 4,
    "protocols": ["V2Ray", "Shadowsocks"],
    "features": ["海外中转", "轻度使用", "基础流媒体"],
    "tags": ["海外中转", "低价", "流媒体"],
    "status": "待核实AFF",
    "description": "海外中转线路，适合轻度访问和基础流媒体需求。",
    "affUrl": "https://ly888.liydl.com:8888/#/register?code=ihbhLNee",
    "promoCode": null,
    "reviewUrl": "airport-review.html?id=liyun",
    "avgSpeed": 280,
    "avgLatency": 48,
    "stability": 95.9
  },
  {
    "id": "caifuyun",
    "name": "财路云",
    "nameEn": "Caifuyun",
    "icon": "CF",
    "tier": "入门",
    "rating": 3.5,
    "price": { "monthly": 7, "quarterly": 19, "yearly": 68 },
    "traffic": "100GB/月起",
    "devices": 4,
    "protocols": ["V2Ray", "Shadowsocks"],
    "features": ["海外中转", "低价套餐", "备用线路"],
    "tags": ["海外中转", "低价", "备用"],
    "status": "待核实AFF",
    "description": "低价海外中转线路，适合预算有限的备用需求。",
    "affUrl": "https://cl888.cailudl.com:9999/#/register?code=d4UTPba8",
    "promoCode": null,
    "reviewUrl": "airport-review.html?id=caifuyun",
    "avgSpeed": 270,
    "avgLatency": 50,
    "stability": 95.6
  }
];
