// 代理软件完整数据库 - 各平台应用齐全版本
const APPS_DATA = [
  // === iOS 应用 ===
  {
    id: 'shadowrocket',
    name: 'Shadowrocket',
    icon: 'SR',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/b9f1730ce334380cb9bb8190e14af7aa.webp',
    developer: 'Shadow Launch Technology',
    platforms: ['ios', 'mac'],
    core: '自研',
    codeStatus: '未公开',
    price: '付费',
    featured: '推荐代理',
    tags: ['自研', '未公开', '$2.99', 'iOS', 'Mac'],
    description: '适用于 iPhone、iPad 与 Apple Silicon Mac 的规则代理工具，可按域名、IP 与 GeoIP 分流，并记录 HTTP、HTTPS 和 DNS 请求。',
    downloadUrl: 'https://apps.apple.com/app/shadowrocket/id932747118',
    version: '2.2.92',
    updated: '2026年9月7日',
    guide: {
      quickStart: '在 App Store 购买并下载应用，首次打开时点击「添加配置」，选择「订阅」或「扫描二维码」导入节点，然后在主界面选择节点并开启连接。',
      features: ['原生性能优化，运行稳定流畅', '完善的规则配置和策略管理', '支持多种代理协议'],
      tips: ['请通过官方渠道购买以获得持续更新和支持', '首次使用需要在系统设置中允许添加 VPN 配置']
    }
  },
  {
    id: 'quantumult-x',
    name: 'Quantumult X',
    icon: 'QX',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/4d62da721dd6b99a538f388b599ecfd3.webp',
    developer: 'Cross Utility',
    platforms: ['ios', 'mac'],
    core: '自研',
    codeStatus: '未公开',
    price: '付费',
    featured: '高级用户',
    tags: ['自研', '未公开', '$7.99', 'iOS', 'Mac'],
    description: '功能强大的网络调试工具，支持策略组、脚本、重写规则和 MitM，适合高级用户。',
    downloadUrl: 'https://apps.apple.com/app/quantumult-x/id1443988620',
    version: '1.4.11',
    updated: '2026年9月5日',
    guide: {
      quickStart: '在 App Store 购买并下载应用，首次打开时点击「添加配置」，选择「订阅」或「扫描二维码」导入节点，然后在主界面选择节点并开启连接。',
      features: ['原生性能优化，运行稳定流畅', '完善的规则配置和策略管理', '支持多种代理协议'],
      tips: ['请通过官方渠道购买以获得持续更新和支持', '首次使用需要在系统设置中允许添加 VPN 配置']
    }
  },
  {
    id: 'surge-ios',
    name: 'Surge',
    icon: 'SG',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/5c4d0108ecaa5f3c21fe51a6737bb6f4.webp',
    developer: 'Surge Networks',
    platforms: ['ios', 'mac'],
    core: '自研',
    codeStatus: '未公开',
    price: '付费',
    featured: '企业级',
    tags: ['自研', '未公开', '订阅制', 'iOS', 'Mac'],
    description: '企业级网络调试工具，功能最强大，支持 HTTP/HTTPS/DNS 流量劫持、MitM 和性能监控。',
    downloadUrl: 'https://apps.apple.com/app/surge-5/id1442620678',
    version: '5.11.0',
    updated: '2026年9月10日',
    guide: {
      quickStart: '在 App Store 购买并下载应用，首次打开时点击「添加配置」，选择「订阅」或「扫描二维码」导入节点，然后在主界面选择节点并开启连接。',
      features: ['原生性能优化，运行稳定流畅', '完善的规则配置和策略管理', '支持多种代理协议', '企业级功能，支持高级网络调试'],
      tips: ['请通过官方渠道购买以获得持续更新和支持', '首次使用需要在系统设置中允许添加 VPN 配置']
    }
  },
  {
    id: 'loon',
    name: 'Loon',
    icon: 'LN',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/5f8fc6e0b996572e050831e94398dd8d.webp',
    developer: 'Loon Network',
    platforms: ['ios', 'mac'],
    core: '自研',
    codeStatus: '未公开',
    price: '付费',
    featured: '策略组',
    tags: ['自研', '未公开', '$5.99', 'iOS', 'Mac'],
    description: '功能强大的网络调试工具，支持策略组、脚本、MitM 等高级功能，界面美观。',
    downloadUrl: 'https://apps.apple.com/app/loon/id1373567447',
    version: '3.2.3',
    updated: '2026年9月3日',
    guide: {
      quickStart: '在 App Store 购买并下载应用，首次打开时点击「添加配置」，选择「订阅」或「扫描二维码」导入节点，然后在主界面选择节点并开启连接。',
      features: ['原生性能优化，运行稳定流畅', '完善的规则配置和策略管理', '支持多种代理协议'],
      tips: ['请通过官方渠道购买以获得持续更新和支持', '首次使用需要在系统设置中允许添加 VPN 配置']
    }
  },
  {
    id: 'stash',
    name: 'Stash',
    icon: 'ST',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/efb59e807d04aac309f7426a99880b23.webp',
    developer: 'Stash Networks',
    platforms: ['ios', 'mac', 'android', 'windows'],
    core: 'clash-rs',
    codeStatus: '部分开源',
    price: '付费',
    featured: 'Clash兼容',
    tags: ['clash-rs', '部分开源', '$3.99', 'iOS', 'Mac'],
    description: '基于 Clash 的图形客户端，支持规则集和脚本，界面简洁易用。',
    downloadUrl: 'https://apps.apple.com/app/stash/id1596063349',
    version: '2.5.1',
    updated: '2026年9月8日',
    guide: {
      quickStart: '在 App Store 购买并下载应用，首次打开时点击「添加配置」，选择「订阅」或「扫描二维码」导入节点，然后在主界面选择节点并开启连接。',
      features: ['跨平台支持，配置可同步'],
      tips: ['请通过官方渠道购买以获得持续更新和支持', '首次使用需要在系统设置中允许添加 VPN 配置', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'spectre',
    name: 'Spectre',
    icon: 'SP',
    developer: 'Spectre Team',
    platforms: ['ios'],
    core: 'Xray',
    codeStatus: '未公开',
    price: '付费',
    featured: '轻量级',
    tags: ['Xray', '未公开', '$1.99', 'iOS'],
    description: '轻量级 iOS 代理工具，基于 Xray 核心，支持多种协议和订阅管理。',
    downloadUrl: 'https://apps.apple.com/app/spectre-vpn/id1508712998',
    version: '2.1.5',
    updated: '2026年8月28日',
    guide: {
      quickStart: '在 App Store 购买并下载应用，首次打开时点击「添加配置」，选择「订阅」或「扫描二维码」导入节点，然后在主界面选择节点并开启连接。',
      features: ['支持 VMess/VLESS/Trojan 等多种协议', '灵活的路由规则配置', '多种传输方式（TCP/WebSocket/gRPC）'],
      tips: ['建议优先使用 WebSocket+TLS 传输以获得更好的稳定性', '可以配置多个服务器作为备用', '路由规则可以实现国内外分流', '请通过官方渠道购买以获得持续更新和支持', '首次使用需要在系统设置中允许添加 VPN 配置']
    }
  },
  {
    id: 'pharos-pro',
    name: 'Pharos Pro',
    icon: 'PP',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/dc2338345d64b6c3a3aa5125ac588c8a.webp',
    developer: 'Pharos Team',
    platforms: ['ios'],
    core: 'sing-box',
    codeStatus: '未公开',
    price: '付费',
    featured: '新协议',
    tags: ['sing-box', '未公开', '$4.99', 'iOS'],
    description: '基于 sing-box 的 iOS 客户端，支持 Reality、Hysteria2 等新协议。',
    downloadUrl: 'https://apps.apple.com/app/pharos-pro/id1456610173',
    version: '3.0.2',
    updated: '2026年9月11日',
    guide: {
      quickStart: '在 App Store 购买并下载应用，首次打开时点击「添加配置」，选择「订阅」或「扫描二维码」导入节点，然后在主界面选择节点并开启连接。',
      features: ['支持最新协议（Reality/Hysteria2/TUIC）', '高性能通用代理平台', '完整的规则路由系统'],
      tips: ['支持最新的 Reality 协议，隐蔽性更强', '可以配置规则集实现精准分流', '请通过官方渠道购买以获得持续更新和支持', '首次使用需要在系统设置中允许添加 VPN 配置']
    }
  },

  // === Android 应用（46款）===
  {
    id: 'v2rayng',
    name: 'v2rayNG',
    icon: 'V2G',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/6e523590968b18d32ef936dee3cbd276.webp',
    developer: '2dust',
    platforms: ['android'],
    core: 'Xray',
    codeStatus: '开源',
    price: '免费',
    featured: '多协议',
    tags: ['Xray', '开源', '免费', 'Android'],
    description: '面向 Android 的 V2Ray 图形客户端，可按域名与 GeoIP 分流，并使用多种传输方式。',
    downloadUrl: 'https://github.com/2dust/v2rayNG/releases',
    version: '1.9.8',
    updated: '2026年9月12日',
    guide: {
      quickStart: '下载安装后，点击右上角「+」→「订阅设置」，添加订阅地址并更新，返回主界面选择服务器节点，点击右下角按钮连接。',
      features: ['支持 VMess/VLESS/Trojan 等多种协议', '灵活的路由规则配置', '多种传输方式（TCP/WebSocket/gRPC）', '完全开源，代码透明可审计'],
      tips: ['建议优先使用 WebSocket+TLS 传输以获得更好的稳定性', '可以配置多个服务器作为备用', '路由规则可以实现国内外分流', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'clash-meta-android',
    name: 'Clash Meta for Android',
    icon: 'CM',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/06702c7634af59ded625d3960c8450e3.webp',
    developer: 'MetaCubeX',
    platforms: ['android'],
    core: 'Mihomo',
    codeStatus: '开源',
    price: '免费',
    featured: '内核新',
    tags: ['Mihomo', '开源', '免费', 'Android'],
    description: 'MetaCubeX 提供的 Android Mihomo 图形客户端，支持最新 Clash Meta 特性。',
    downloadUrl: 'https://github.com/MetaCubeX/ClashMetaForAndroid/releases',
    version: '2.10.3',
    updated: '2026年8月25日',
    guide: {
      quickStart: '安装后打开应用，点击「配置」→「新建配置」→「URL」，粘贴订阅链接并保存，返回主界面选择配置文件，点击连接按钮即可开始使用。',
      features: ['支持 Clash 规则集和策略组', '内置规则分流和 GeoIP 数据库', '实时流量统计和节点延迟测试', '完全开源，代码透明可审计'],
      tips: ['建议启用自动更新订阅，保持节点列表最新', '可以通过策略组实现自动选择最优节点', '定期测速以获得最佳连接体验', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'surfboard',
    name: 'Surfboard',
    icon: 'SF',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/159522b189ea6c2d00b87bf2703d6cee.webp',
    developer: 'Surfboard Team',
    platforms: ['android'],
    core: '自研',
    codeStatus: '未公开',
    price: '免费',
    featured: 'Surge风格',
    tags: ['自研', '未公开', '免费', 'Android'],
    description: 'Android 平台的 Surge 风格客户端，支持 Surge 配置格式和规则。',
    downloadUrl: 'https://play.google.com/store/apps/details?id=com.getsurfboard',
    version: '2.29.3',
    updated: '2026年9月14日',
    guide: {
      quickStart: '下载并安装应用，打开后添加服务器配置或订阅链接，选择节点后启用连接即可开始使用。',
      features: ['原生性能优化，运行稳定流畅', '完善的规则配置和策略管理', '支持多种代理协议'],
      tips: ['应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'clash-for-android',
    name: 'Clash for Android',
    icon: 'CFA',
    developer: 'Kr328',
    platforms: ['android'],
    core: 'Clash',
    codeStatus: '开源',
    price: '免费',
    featured: '经典',
    tags: ['Clash', '开源', '免费', 'Android'],
    description: 'Android 平台经典的 Clash 客户端（已停止更新），稳定可靠。',
    downloadUrl: 'https://github.com/Kr328/ClashForAndroid/releases',
    version: '2.5.12',
    updated: '2023年10月12日',
    guide: {
      quickStart: '安装后打开应用，点击「配置」→「新建配置」→「URL」，粘贴订阅链接并保存，返回主界面选择配置文件，点击连接按钮即可开始使用。',
      features: ['支持 Clash 规则集和策略组', '内置规则分流和 GeoIP 数据库', '实时流量统计和节点延迟测试', '完全开源，代码透明可审计'],
      tips: ['建议启用自动更新订阅，保持节点列表最新', '可以通过策略组实现自动选择最优节点', '定期测速以获得最佳连接体验', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'matsuri',
    name: 'Matsuri',
    icon: 'MT',
    developer: 'Matsuri Team',
    platforms: ['android'],
    core: 'sing-box',
    codeStatus: '开源',
    price: '免费',
    featured: '插件系统',
    tags: ['sing-box', '开源', '免费', 'Android'],
    description: '基于 NekoBox 的分支版本，支持插件系统和多种协议。',
    downloadUrl: 'https://github.com/MatsuriDayo/Matsuri/releases',
    version: '1.3.6',
    updated: '2026年9月6日',
    guide: {
      quickStart: '安装应用后，点击「配置」→「添加」→「从 URL 导入」，输入订阅链接，选择配置文件后点击连接按钮启动代理。',
      features: ['支持最新协议（Reality/Hysteria2/TUIC）', '高性能通用代理平台', '完整的规则路由系统', '完全开源，代码透明可审计'],
      tips: ['支持最新的 Reality 协议，隐蔽性更强', '可以配置规则集实现精准分流', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'sagernet',
    name: 'SagerNet',
    icon: 'SN',
    developer: 'SagerNet',
    platforms: ['android'],
    core: 'sing-box',
    codeStatus: '开源',
    price: '免费',
    featured: '多核心',
    tags: ['sing-box', '开源', '免费', 'Android'],
    description: 'Android 通用代理工具箱，支持多种核心和协议（已停止更新）。',
    downloadUrl: 'https://github.com/SagerNet/SagerNet/releases',
    version: '0.10.2',
    updated: '2024年3月15日',
    guide: {
      quickStart: '安装应用后，点击「配置」→「添加」→「从 URL 导入」，输入订阅链接，选择配置文件后点击连接按钮启动代理。',
      features: ['支持最新协议（Reality/Hysteria2/TUIC）', '高性能通用代理平台', '完整的规则路由系统', '完全开源，代码透明可审计'],
      tips: ['支持最新的 Reality 协议，隐蔽性更强', '可以配置规则集实现精准分流', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'nekobox-android',
    name: 'NekoBox for Android',
    icon: 'NB',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/3765d4be7c293f40f754cd2e48b400c9.webp',
    developer: 'MatsuriDayo',
    platforms: ['android'],
    core: 'sing-box',
    codeStatus: '开源',
    price: '免费',
    featured: '轻量',
    tags: ['sing-box', '开源', '免费', 'Android'],
    description: '基于 sing-box 的 Android 客户端，界面简洁，功能完整。',
    downloadUrl: 'https://github.com/MatsuriDayo/NekoBoxForAndroid/releases',
    version: '1.3.2',
    updated: '2026年9月7日',
    guide: {
      quickStart: '安装应用后，点击「配置」→「添加」→「从 URL 导入」，输入订阅链接，选择配置文件后点击连接按钮启动代理。',
      features: ['支持最新协议（Reality/Hysteria2/TUIC）', '高性能通用代理平台', '完整的规则路由系统', '完全开源，代码透明可审计'],
      tips: ['支持最新的 Reality 协议，隐蔽性更强', '可以配置规则集实现精准分流', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'shadowsocks-android',
    name: 'Shadowsocks Android',
    icon: 'SSA',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/fba92cee640e3d5c5566477c1d8a4fcb.webp',
    developer: 'shadowsocks',
    platforms: ['android'],
    core: 'Shadowsocks',
    codeStatus: '开源',
    price: '免费',
    featured: '官方版',
    tags: ['Shadowsocks', '开源', '免费', 'Android'],
    description: 'Shadowsocks 官方 Android 客户端，稳定可靠，功能完善。',
    downloadUrl: 'https://github.com/shadowsocks/shadowsocks-android/releases',
    version: '5.3.3',
    updated: '2026年8月15日',
    guide: {
      quickStart: '下载并安装应用，打开后添加服务器配置或订阅链接，选择节点后启用连接即可开始使用。',
      features: ['完全开源，代码透明可审计'],
      tips: ['遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'shadowsocksr-android',
    name: 'ShadowsocksR Android',
    icon: 'SSRA',
    developer: 'shadowsocksrr',
    platforms: ['android'],
    core: 'SSR',
    codeStatus: '开源',
    price: '免费',
    featured: 'SSR',
    tags: ['SSR', '开源', '免费', 'Android'],
    description: 'ShadowsocksR Android 客户端，支持混淆和协议插件。',
    downloadUrl: 'https://github.com/HMBSbige/ShadowsocksR-Android/releases',
    version: '3.5.4',
    updated: '2023年6月10日',
    guide: {
      quickStart: '下载并安装应用，打开后添加服务器配置或订阅链接，选择节点后启用连接即可开始使用。',
      features: ['完全开源，代码透明可审计'],
      tips: ['遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'v2fly',
    name: 'V2Fly',
    icon: 'V2F',
    developer: 'V2Fly',
    platforms: ['android'],
    core: 'V2Ray',
    codeStatus: '开源',
    price: '免费',
    featured: 'V2Fly社区',
    tags: ['V2Ray', '开源', '免费', 'Android'],
    description: 'V2Fly 社区维护的 Android 客户端，继承 V2Ray 官方版本。',
    downloadUrl: 'https://github.com/2dust/v2flyNG/releases',
    version: '1.8.19',
    updated: '2026年8月28日',
    guide: {
      quickStart: '下载安装后，点击右上角「+」→「订阅设置」，添加订阅地址并更新，返回主界面选择服务器节点，点击右下角按钮连接。',
      features: ['支持 VMess/VLESS/Trojan 等多种协议', '灵活的路由规则配置', '多种传输方式（TCP/WebSocket/gRPC）', '完全开源，代码透明可审计'],
      tips: ['建议优先使用 WebSocket+TLS 传输以获得更好的稳定性', '可以配置多个服务器作为备用', '路由规则可以实现国内外分流', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'kitsunebi-android',
    name: 'Kitsunebi',
    icon: 'KB',
    developer: 'eycorsican',
    platforms: ['android'],
    core: 'V2Ray',
    codeStatus: '开源',
    price: '免费',
    featured: '轻量级',
    tags: ['V2Ray', '开源', '免费', 'Android'],
    description: '轻量级 V2Ray Android 客户端，界面简洁。',
    downloadUrl: 'https://github.com/eycorsican/kitsunebi-android/releases',
    version: '1.8.0',
    updated: '2022年5月12日',
    guide: {
      quickStart: '下载安装后，点击右上角「+」→「订阅设置」，添加订阅地址并更新，返回主界面选择服务器节点，点击右下角按钮连接。',
      features: ['支持 VMess/VLESS/Trojan 等多种协议', '灵活的路由规则配置', '多种传输方式（TCP/WebSocket/gRPC）', '完全开源，代码透明可审计'],
      tips: ['建议优先使用 WebSocket+TLS 传输以获得更好的稳定性', '可以配置多个服务器作为备用', '路由规则可以实现国内外分流', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'bitsrun-android',
    name: 'BifrostV',
    icon: 'BF',
    developer: 'Bitsrun',
    platforms: ['android'],
    core: 'V2Ray',
    codeStatus: '未公开',
    price: '免费',
    tags: ['V2Ray', '未公开', '免费', 'Android'],
    description: 'Android 平台 V2Ray 客户端，支持订阅和导入。',
    downloadUrl: 'https://play.google.com/store/apps/details?id=com.github.dawndiy.bifrostv',
    version: '0.7.3',
    updated: '2023年3月8日',
    guide: {
      quickStart: '下载安装后，点击右上角「+」→「订阅设置」，添加订阅地址并更新，返回主界面选择服务器节点，点击右下角按钮连接。',
      features: ['支持 VMess/VLESS/Trojan 等多种协议', '灵活的路由规则配置', '多种传输方式（TCP/WebSocket/gRPC）'],
      tips: ['建议优先使用 WebSocket+TLS 传输以获得更好的稳定性', '可以配置多个服务器作为备用', '路由规则可以实现国内外分流', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'pharos-android',
    name: 'Pharos',
    icon: 'PH',
    developer: 'Pharos Team',
    platforms: ['android'],
    core: 'sing-box',
    codeStatus: '开源',
    price: '免费',
    featured: '新协议',
    tags: ['sing-box', '开源', '免费', 'Android'],
    description: '支持最新协议的 Android 客户端，基于 sing-box 核心。',
    downloadUrl: 'https://github.com/pharos-systems/pharos/releases',
    version: '2.1.0',
    updated: '2026年9月9日',
    guide: {
      quickStart: '安装应用后，点击「配置」→「添加」→「从 URL 导入」，输入订阅链接，选择配置文件后点击连接按钮启动代理。',
      features: ['支持最新协议（Reality/Hysteria2/TUIC）', '高性能通用代理平台', '完整的规则路由系统', '完全开源，代码透明可审计'],
      tips: ['支持最新的 Reality 协议，隐蔽性更强', '可以配置规则集实现精准分流', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'shadowrocket-android',
    name: 'SocksDroid',
    icon: 'SD',
    developer: 'SocksDroid',
    platforms: ['android'],
    core: 'Shadowsocks',
    codeStatus: '开源',
    price: '免费',
    tags: ['Shadowsocks', '开源', '免费', 'Android'],
    description: 'Android 平台 Shadowsocks 客户端，支持 SOCKS5 代理。',
    downloadUrl: 'https://github.com/bige0/socksdroid/releases',
    version: '1.0.5',
    updated: '2021年7月22日',
    guide: {
      quickStart: '下载并安装应用，打开后添加服务器配置或订阅链接，选择节点后启用连接即可开始使用。',
      features: ['完全开源，代码透明可审计'],
      tips: ['遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'shadowsocks-libev-android',
    name: 'SS-Libev Android',
    icon: 'SSL',
    developer: 'shadowsocks',
    platforms: ['android'],
    core: 'Shadowsocks',
    codeStatus: '开源',
    price: '免费',
    tags: ['Shadowsocks', '开源', '免费', 'Android'],
    description: 'Shadowsocks-libev Android 版本，性能优秀。',
    downloadUrl: 'https://github.com/shadowsocks/shadowsocks-libev/releases',
    version: '3.3.5',
    updated: '2021年1月3日',
    guide: {
      quickStart: '下载并安装应用，打开后添加服务器配置或订阅链接，选择节点后启用连接即可开始使用。',
      features: ['完全开源，代码透明可审计'],
      tips: ['遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'outline-android',
    name: 'Outline',
    icon: 'OL',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/3765b64c79b4e9cf9e686a319fa565fa.webp',
    developer: 'Jigsaw',
    platforms: ['android'],
    core: 'Shadowsocks',
    codeStatus: '开源',
    price: '免费',
    featured: 'Google出品',
    tags: ['Shadowsocks', '开源', '免费', 'Android'],
    description: 'Google Jigsaw 开发的 Shadowsocks 客户端，简单易用。',
    downloadUrl: 'https://play.google.com/store/apps/details?id=org.outline.android.client',
    version: '1.14.0',
    updated: '2026年8月5日',
    guide: {
      quickStart: '下载并安装应用，打开后添加服务器配置或订阅链接，选择节点后启用连接即可开始使用。',
      features: ['完全开源，代码透明可审计'],
      tips: ['遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'trojan-go-android',
    name: 'Trojan-Go Android',
    icon: 'TG',
    developer: 'Trojan-Go',
    platforms: ['android'],
    core: 'Trojan',
    codeStatus: '开源',
    price: '免费',
    tags: ['Trojan', '开源', '免费', 'Android'],
    description: 'Trojan-Go 协议 Android 客户端，支持多路复用。',
    downloadUrl: 'https://github.com/p4gefau1t/trojan-go-android/releases',
    version: '0.10.6',
    updated: '2023年9月14日',
    guide: {
      quickStart: '下载并安装应用，打开后添加服务器配置或订阅链接，选择节点后启用连接即可开始使用。',
      features: ['完全开源，代码透明可审计'],
      tips: ['遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'igniter-android',
    name: 'Igniter',
    icon: 'IG',
    developer: 'Trojan',
    platforms: ['android'],
    core: 'Trojan',
    codeStatus: '开源',
    price: '免费',
    tags: ['Trojan', '开源', '免费', 'Android'],
    description: 'Trojan 协议 Android 客户端，界面友好。',
    downloadUrl: 'https://github.com/trojan-gfw/igniter/releases',
    version: '0.9.9',
    updated: '2021年11月8日',
    guide: {
      quickStart: '下载并安装应用，打开后添加服务器配置或订阅链接，选择节点后启用连接即可开始使用。',
      features: ['完全开源，代码透明可审计'],
      tips: ['遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'clash-magisk',
    name: 'Clash For Magisk',
    icon: 'CFM',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/2ef50c56742839bf0004bae672145726.webp',
    developer: 'taamarin',
    platforms: ['android'],
    core: 'Clash',
    codeStatus: '开源',
    price: '免费',
    featured: 'Magisk模块',
    tags: ['Clash', '开源', '免费', 'Magisk'],
    description: 'Magisk 模块形式的 Clash，无需独立应用。',
    downloadUrl: 'https://github.com/taamarin/box_for_magisk/releases',
    version: '1.1.8',
    updated: '2026年9月9日',
    guide: {
      quickStart: '安装后打开应用，点击「配置」→「新建配置」→「URL」，粘贴订阅链接并保存，返回主界面选择配置文件，点击连接按钮即可开始使用。',
      features: ['支持 Clash 规则集和策略组', '内置规则分流和 GeoIP 数据库', '实时流量统计和节点延迟测试', '完全开源，代码透明可审计'],
      tips: ['建议启用自动更新订阅，保持节点列表最新', '可以通过策略组实现自动选择最优节点', '定期测速以获得最佳连接体验', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'ssr-magisk',
    name: 'SSR For Magisk',
    icon: 'SRM',
    developer: 'KaguraKernel',
    platforms: ['android'],
    core: 'SSR',
    codeStatus: '开源',
    price: '免费',
    tags: ['SSR', '开源', '免费', 'Magisk'],
    description: 'Magisk 模块形式的 SSR 客户端。',
    downloadUrl: 'https://github.com/Kr328/Riru-ShadowsocksR/releases',
    version: '3.0.2',
    updated: '2022年4月15日',
    guide: {
      quickStart: '下载并安装应用，打开后添加服务器配置或订阅链接，选择节点后启用连接即可开始使用。',
      features: ['完全开源，代码透明可审计'],
      tips: ['遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'postern-android',
    name: 'Postern',
    icon: 'PS',
    developer: 'TunnelWorkshop',
    platforms: ['android'],
    core: '多核心',
    codeStatus: '未公开',
    price: '付费',
    tags: ['多核心', '未公开', '$2.99', 'Android'],
    description: 'Android 平台专业代理工具，支持多种协议和规则。',
    downloadUrl: 'https://play.google.com/store/apps/details?id=com.tunnelworkshop.postern',
    version: '3.1.3',
    updated: '2024年6月20日',
    guide: {
      quickStart: '下载并安装应用，打开后添加服务器配置或订阅链接，选择节点后启用连接即可开始使用。',
      features: [],
      tips: ['请通过官方渠道购买以获得持续更新和支持', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'drony-android',
    name: 'Drony',
    icon: 'DR',
    developer: 'Drony',
    platforms: ['android'],
    core: '多核心',
    codeStatus: '未公开',
    price: '免费',
    tags: ['多核心', '未公开', '免费', 'Android'],
    description: 'Android 平台网络规则工具，支持代理和防火墙。',
    downloadUrl: 'https://play.google.com/store/apps/details?id=org.sandroproxy.drony',
    version: '1.3.163',
    updated: '2021年8月30日',
    guide: {
      quickStart: '下载并安装应用，打开后添加服务器配置或订阅链接，选择节点后启用连接即可开始使用。',
      features: [],
      tips: ['应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'clash-premium-android',
    name: 'Clash Premium',
    icon: 'CP',
    developer: 'Premium Core',
    platforms: ['android'],
    core: 'Clash Premium',
    codeStatus: '未公开',
    price: '免费',
    tags: ['Clash', '未公开', '免费', 'Android'],
    description: '集成 Clash Premium 核心的 Android 客户端。',
    downloadUrl: 'https://github.com/Dreamacro/clash/releases',
    version: '2023.08.17',
    updated: '2023年8月17日',
    guide: {
      quickStart: '下载并安装应用，打开后添加服务器配置或订阅链接，选择节点后启用连接即可开始使用。',
      features: [],
      tips: ['应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'shadowsocksd-android',
    name: 'ShadowsocksD',
    icon: 'SSD',
    developer: 'ShadowsocksD',
    platforms: ['android'],
    core: 'Shadowsocks',
    codeStatus: '开源',
    price: '免费',
    tags: ['Shadowsocks', '开源', '免费', 'Android'],
    description: 'Shadowsocks 衍生版本，增强功能。',
    downloadUrl: 'https://github.com/TheCGDF/SSD-Android/releases',
    version: '1.0.8',
    updated: '2020年9月5日',
    guide: {
      quickStart: '下载并安装应用，打开后添加服务器配置或订阅链接，选择节点后启用连接即可开始使用。',
      features: ['完全开源，代码透明可审计'],
      tips: ['遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'simple-obfs-android',
    name: 'Simple Obfs',
    icon: 'SO',
    developer: 'shadowsocks',
    platforms: ['android'],
    core: 'Shadowsocks',
    codeStatus: '开源',
    price: '免费',
    tags: ['Shadowsocks', '开源', '免费', 'Android'],
    description: 'Shadowsocks 混淆插件 Android 版本。',
    downloadUrl: 'https://github.com/shadowsocks/simple-obfs-android/releases',
    version: '0.0.5',
    updated: '2019年3月12日',
    guide: {
      quickStart: '下载并安装应用，打开后添加服务器配置或订阅链接，选择节点后启用连接即可开始使用。',
      features: ['完全开源，代码透明可审计'],
      tips: ['遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'kcptun-android',
    name: 'Kcptun Android',
    icon: 'KT',
    developer: 'Kcptun',
    platforms: ['android'],
    core: 'KCP',
    codeStatus: '开源',
    price: '免费',
    tags: ['KCP', '开源', '免费', 'Android'],
    description: 'KCP 协议 Android 客户端，适合高丢包网络。',
    downloadUrl: 'https://github.com/shadowsocks/kcptun-android/releases',
    version: '20171021',
    updated: '2017年10月21日',
    guide: {
      quickStart: '下载并安装应用，打开后添加服务器配置或订阅链接，选择节点后启用连接即可开始使用。',
      features: ['完全开源，代码透明可审计'],
      tips: ['遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'brook-android',
    name: 'Brook',
    icon: 'BK',
    developer: 'txthinking',
    platforms: ['android'],
    core: 'Brook',
    codeStatus: '开源',
    price: '免费',
    tags: ['Brook', '开源', '免费', 'Android'],
    description: 'Brook 协议 Android 客户端，简单高效。',
    downloadUrl: 'https://github.com/txthinking/brook/releases',
    version: '20230401',
    updated: '2023年4月1日',
    guide: {
      quickStart: '下载并安装应用，打开后添加服务器配置或订阅链接，选择节点后启用连接即可开始使用。',
      features: ['完全开源，代码透明可审计'],
      tips: ['遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'cloak-android',
    name: 'Cloak',
    icon: 'CL',
    developer: 'cbeuw',
    platforms: ['android'],
    core: 'Cloak',
    codeStatus: '开源',
    price: '免费',
    tags: ['Cloak', '开源', '免费', 'Android'],
    description: 'Cloak 流量混淆工具 Android 版本。',
    downloadUrl: 'https://github.com/cbeuw/Cloak-android/releases',
    version: '2.6.1',
    updated: '2023年7月8日',
    guide: {
      quickStart: '下载并安装应用，打开后添加服务器配置或订阅链接，选择节点后启用连接即可开始使用。',
      features: ['完全开源，代码透明可审计'],
      tips: ['遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'geph-android',
    name: 'Geph',
    icon: 'GP',
    developer: 'Geph',
    platforms: ['android'],
    core: 'Geph',
    codeStatus: '开源',
    price: '付费',
    tags: ['Geph', '开源', '订阅制', 'Android'],
    description: 'Geph 协议 Android 客户端，抗封锁能力强。',
    downloadUrl: 'https://geph.io/download/',
    version: '4.9.7',
    updated: '2026年9月11日',
    guide: {
      quickStart: '下载并安装应用，打开后添加服务器配置或订阅链接，选择节点后启用连接即可开始使用。',
      features: ['完全开源，代码透明可审计'],
      tips: ['遇到问题可在 GitHub 提交 Issue 获得社区支持', '请通过官方渠道购买以获得持续更新和支持', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'lantern-android',
    name: 'Lantern',
    icon: 'LT',
    developer: 'Brave New Software',
    platforms: ['android'],
    core: '自研',
    codeStatus: '开源',
    price: '免费增值',
    tags: ['自研', '开源', '免费增值', 'Android'],
    description: '蓝灯 Android 客户端，一键连接，操作简单。',
    downloadUrl: 'https://github.com/getlantern/lantern/releases',
    version: '7.8.5',
    updated: '2026年9月3日',
    guide: {
      quickStart: '下载并安装应用，打开后添加服务器配置或订阅链接，选择节点后启用连接即可开始使用。',
      features: ['原生性能优化，运行稳定流畅', '完善的规则配置和策略管理', '支持多种代理协议', '完全开源，代码透明可审计'],
      tips: ['遇到问题可在 GitHub 提交 Issue 获得社区支持', '请通过官方渠道购买以获得持续更新和支持', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'psiphon-android',
    name: 'Psiphon',
    icon: 'PI',
    developer: 'Psiphon Inc',
    platforms: ['android'],
    core: '自研',
    codeStatus: '开源',
    price: '免费',
    tags: ['自研', '开源', '免费', 'Android'],
    description: 'Psiphon Android 客户端，自动选择最佳服务器。',
    downloadUrl: 'https://psiphon.ca/download.html',
    version: '369',
    updated: '2026年9月4日',
    guide: {
      quickStart: '下载并安装应用，打开后添加服务器配置或订阅链接，选择节点后启用连接即可开始使用。',
      features: ['原生性能优化，运行稳定流畅', '完善的规则配置和策略管理', '支持多种代理协议', '完全开源，代码透明可审计'],
      tips: ['遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'ultrasurf-android',
    name: 'Ultrasurf',
    icon: 'US',
    developer: 'UltraReach',
    platforms: ['android'],
    core: '自研',
    codeStatus: '未公开',
    price: '免费',
    tags: ['自研', '未公开', '免费', 'Android'],
    description: 'Ultrasurf Android 版本，一键连接。',
    downloadUrl: 'https://ultrasurf.us/',
    version: '2.3.2',
    updated: '2026年8月22日',
    guide: {
      quickStart: '下载并安装应用，打开后添加服务器配置或订阅链接，选择节点后启用连接即可开始使用。',
      features: ['原生性能优化，运行稳定流畅', '完善的规则配置和策略管理', '支持多种代理协议'],
      tips: ['应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'betternet-android',
    name: 'Betternet',
    icon: 'BN',
    developer: 'Betternet',
    platforms: ['android'],
    core: '自研',
    codeStatus: '未公开',
    price: '免费增值',
    tags: ['自研', '未公开', '免费增值', 'Android'],
    description: 'Betternet Android VPN 客户端，无需注册。',
    downloadUrl: 'https://play.google.com/store/apps/details?id=com.freevpnintouch',
    version: '5.9.0',
    updated: '2026年8月15日',
    guide: {
      quickStart: '下载并安装应用，打开后添加服务器配置或订阅链接，选择节点后启用连接即可开始使用。',
      features: ['原生性能优化，运行稳定流畅', '完善的规则配置和策略管理', '支持多种代理协议'],
      tips: ['请通过官方渠道购买以获得持续更新和支持', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'vpnhub-android',
    name: 'VPNhub',
    icon: 'VH',
    developer: 'AppAtomic',
    platforms: ['android'],
    core: '自研',
    codeStatus: '未公开',
    price: '免费增值',
    tags: ['自研', '未公开', '免费增值', 'Android'],
    description: 'VPNhub Android 客户端，简单快速。',
    downloadUrl: 'https://play.google.com/store/apps/details?id=com.appatomic.vpnhub',
    version: '3.20.14',
    updated: '2026年9月2日',
    guide: {
      quickStart: '下载并安装应用，打开后添加服务器配置或订阅链接，选择节点后启用连接即可开始使用。',
      features: ['原生性能优化，运行稳定流畅', '完善的规则配置和策略管理', '支持多种代理协议'],
      tips: ['请通过官方渠道购买以获得持续更新和支持', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'windscribe-android',
    name: 'Windscribe',
    icon: 'WS',
    developer: 'Windscribe',
    platforms: ['android'],
    core: 'WireGuard',
    codeStatus: '部分开源',
    price: '免费增值',
    tags: ['WireGuard', '部分开源', '免费增值', 'Android'],
    description: 'Windscribe Android VPN，每月 10GB 免费流量。',
    downloadUrl: 'https://play.google.com/store/apps/details?id=com.windscribe.vpn',
    version: '3.74.1',
    updated: '2026年9月10日',
    guide: {
      quickStart: '下载并安装应用，打开后添加服务器配置或订阅链接，选择节点后启用连接即可开始使用。',
      features: [],
      tips: ['请通过官方渠道购买以获得持续更新和支持', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'protonvpn-android',
    name: 'ProtonVPN',
    icon: 'PV',
    developer: 'Proton AG',
    platforms: ['android'],
    core: 'WireGuard',
    codeStatus: '开源',
    price: '免费增值',
    featured: '隐私保护',
    tags: ['WireGuard', '开源', '免费增值', 'Android'],
    description: 'ProtonVPN Android 客户端，注重隐私保护。',
    downloadUrl: 'https://play.google.com/store/apps/details?id=ch.protonvpn.android',
    version: '4.10.79',
    updated: '2026年9月13日',
    guide: {
      quickStart: '下载并安装应用，打开后添加服务器配置或订阅链接，选择节点后启用连接即可开始使用。',
      features: ['完全开源，代码透明可审计'],
      tips: ['遇到问题可在 GitHub 提交 Issue 获得社区支持', '请通过官方渠道购买以获得持续更新和支持', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'mullvad-android',
    name: 'Mullvad VPN',
    icon: 'MV',
    developer: 'Mullvad',
    platforms: ['android'],
    core: 'WireGuard',
    codeStatus: '开源',
    price: '付费',
    featured: '匿名性',
    tags: ['WireGuard', '开源', '€5/月', 'Android'],
    description: 'Mullvad VPN Android 客户端，注重匿名性。',
    downloadUrl: 'https://mullvad.net/download/',
    version: '2024.5',
    updated: '2026年9月8日',
    guide: {
      quickStart: '下载并安装应用，打开后添加服务器配置或订阅链接，选择节点后启用连接即可开始使用。',
      features: ['完全开源，代码透明可审计'],
      tips: ['遇到问题可在 GitHub 提交 Issue 获得社区支持', '请通过官方渠道购买以获得持续更新和支持', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'wireguard-android',
    name: 'WireGuard',
    icon: 'WG',
    developer: 'WireGuard',
    platforms: ['android'],
    core: 'WireGuard',
    codeStatus: '开源',
    price: '免费',
    featured: '官方版',
    tags: ['WireGuard', '开源', '免费', 'Android'],
    description: 'WireGuard 官方 Android 客户端，现代化 VPN 协议。',
    downloadUrl: 'https://play.google.com/store/apps/details?id=com.wireguard.android',
    version: '1.0.20240809',
    updated: '2026年8月9日',
    guide: {
      quickStart: '下载并安装应用，打开后添加服务器配置或订阅链接，选择节点后启用连接即可开始使用。',
      features: ['完全开源，代码透明可审计'],
      tips: ['遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'openvpn-android',
    name: 'OpenVPN for Android',
    icon: 'OVA',
    developer: 'Arne Schwabe',
    platforms: ['android'],
    core: 'OpenVPN',
    codeStatus: '开源',
    price: '免费',
    tags: ['OpenVPN', '开源', '免费', 'Android'],
    description: 'OpenVPN 协议 Android 客户端，功能完整。',
    downloadUrl: 'https://play.google.com/store/apps/details?id=de.blinkt.openvpn',
    version: '0.7.50',
    updated: '2026年8月25日',
    guide: {
      quickStart: '下载并安装应用，打开后添加服务器配置或订阅链接，选择节点后启用连接即可开始使用。',
      features: ['完全开源，代码透明可审计'],
      tips: ['遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'openvpn-connect-android',
    name: 'OpenVPN Connect',
    icon: 'OVC',
    developer: 'OpenVPN Inc',
    platforms: ['android'],
    core: 'OpenVPN',
    codeStatus: '部分开源',
    price: '免费',
    featured: '官方版',
    tags: ['OpenVPN', '部分开源', '免费', 'Android'],
    description: 'OpenVPN 官方 Android 客户端。',
    downloadUrl: 'https://play.google.com/store/apps/details?id=net.openvpn.openvpn',
    version: '3.4.4',
    updated: '2026年9月5日',
    guide: {
      quickStart: '下载并安装应用，打开后添加服务器配置或订阅链接，选择节点后启用连接即可开始使用。',
      features: [],
      tips: ['应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'strongswan-android',
    name: 'strongSwan VPN',
    icon: 'SS',
    developer: 'strongSwan',
    platforms: ['android'],
    core: 'IPSec',
    codeStatus: '开源',
    price: '免费',
    tags: ['IPSec', '开源', '免费', 'Android'],
    description: 'strongSwan IPSec VPN Android 客户端。',
    downloadUrl: 'https://play.google.com/store/apps/details?id=org.strongswan.android',
    version: '2.4.2',
    updated: '2024年3月18日',
    guide: {
      quickStart: '下载并安装应用，打开后添加服务器配置或订阅链接，选择节点后启用连接即可开始使用。',
      features: ['完全开源，代码透明可审计'],
      tips: ['遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'shadowtls-android',
    name: 'ShadowTLS',
    icon: 'STL',
    developer: 'ihciah',
    platforms: ['android'],
    core: 'ShadowTLS',
    codeStatus: '开源',
    price: '免费',
    tags: ['ShadowTLS', '开源', '免费', 'Android'],
    description: 'ShadowTLS 协议 Android 客户端。',
    downloadUrl: 'https://github.com/ihciah/shadow-tls/releases',
    version: '0.2.25',
    updated: '2023年12月5日',
    guide: {
      quickStart: '下载并安装应用，打开后添加服务器配置或订阅链接，选择节点后启用连接即可开始使用。',
      features: ['完全开源，代码透明可审计'],
      tips: ['遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'hysteria-android',
    name: 'Hysteria',
    icon: 'HY',
    developer: 'HyNetwork',
    platforms: ['android'],
    core: 'Hysteria',
    codeStatus: '开源',
    price: '免费',
    tags: ['Hysteria', '开源', '免费', 'Android'],
    description: 'Hysteria 协议 Android 客户端，UDP 加速。',
    downloadUrl: 'https://github.com/HyNetwork/hysteria/releases',
    version: '2.5.0',
    updated: '2026年9月12日',
    guide: {
      quickStart: '下载并安装应用，打开后添加服务器配置或订阅链接，选择节点后启用连接即可开始使用。',
      features: ['完全开源，代码透明可审计'],
      tips: ['遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'tuic-android',
    name: 'TUIC',
    icon: 'TC',
    developer: 'TUIC',
    platforms: ['android'],
    core: 'TUIC',
    codeStatus: '开源',
    price: '免费',
    tags: ['TUIC', '开源', '免费', 'Android'],
    description: 'TUIC 协议 Android 客户端，基于 QUIC。',
    downloadUrl: 'https://github.com/EAimTY/tuic/releases',
    version: '1.0.0',
    updated: '2023年11月28日',
    guide: {
      quickStart: '下载并安装应用，打开后添加服务器配置或订阅链接，选择节点后启用连接即可开始使用。',
      features: ['完全开源，代码透明可审计'],
      tips: ['遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },

  // === Windows 应用 ===
  {
    id: 'v2rayn',
    name: 'v2rayN',
    icon: 'V2N',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/f8b719daa3bf53259aaa8fe2d2921b6f.webp',
    developer: '2dust',
    platforms: ['windows'],
    core: 'Xray',
    codeStatus: '开源',
    price: '免费',
    featured: '多协议',
    tags: ['Xray', '开源', '免费', 'Win'],
    description: '面向 Windows 的 V2Ray 图形客户端，轻量高效，支持多协议和路由规则。',
    downloadUrl: 'https://github.com/2dust/v2rayN/releases',
    version: '7.2.3',
    updated: '2026年9月18日',
    guide: {
      quickStart: '下载解压后运行程序，点击「订阅」→「订阅设置」添加订阅地址，更新订阅后选择服务器节点，启用系统代理即可使用。',
      features: ['支持 VMess/VLESS/Trojan 等多种协议', '灵活的路由规则配置', '多种传输方式（TCP/WebSocket/gRPC）', '完全开源，代码透明可审计'],
      tips: ['建议优先使用 WebSocket+TLS 传输以获得更好的稳定性', '可以配置多个服务器作为备用', '路由规则可以实现国内外分流', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版']
    }
  },
  {
    id: 'clash-verge-rev',
    name: 'Clash Verge Rev',
    icon: 'CV',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/8795e6a5f6f5c34d93d03c58c0a54a02.webp',
    developer: 'Clash Verge Rev Team',
    platforms: ['windows', 'mac', 'linux'],
    core: 'Mihomo',
    codeStatus: '开源',
    price: '免费',
    featured: '桌面推荐',
    tags: ['Mihomo', '开源', '免费', 'Win', 'Mac', 'Linux'],
    description: '基于 Tauri 的 Mihomo 图形客户端，界面美观，功能完整，支持 TUN 模式。',
    downloadUrl: 'https://github.com/clash-verge-rev/clash-verge-rev/releases',
    version: '1.7.7',
    updated: '2026年9月15日',
    guide: {
      quickStart: '下载安装后，点击订阅 → 新建订阅 → 粘贴订阅链接 → 保存，然后在主界面选择节点并开启系统代理。',
      features: ['支持 Mihomo 核心最新特性', '内置 TUN 模式增强', '规则集自动更新', '自定义配置编辑'],
      tips: ['首次使用建议启用 TUN 模式获得最佳体验', '可在设置中配置自动更新订阅', '支持导入 Clash 配置文件']
    }
  },
  {
    id: 'clash-party',
    name: 'Clash Party',
    icon: 'CP',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/clash-party-logo.webp',
    developer: 'mihomo-party-org',
    platforms: ['windows', 'mac', 'linux'],
    core: 'Mihomo',
    codeStatus: '开源',
    price: '免费',
    featured: '2026新锐',
    tags: ['Mihomo', '开源', '免费', 'Win', 'Mac', 'Linux'],
    description: '2026年备受赞誉的跨平台 Mihomo 客户端，基于最新 Mihomo 核心构建，界面现代美观，功能完整。',
    downloadUrl: 'https://github.com/mihomo-party-org/clash-party/releases',
    version: '1.0.8',
    updated: '2026年9月20日',
    guide: {
      quickStart: '安装后首次启动，点击配置 → 添加订阅 → 输入订阅地址 → 确认，然后在主页选择节点并点击连接按钮。',
      features: ['基于最新 Mihomo 核心', '跨平台支持 Windows/Mac/Linux', '现代化 UI 设计', '完整的规则管理', '内置性能监控'],
      tips: ['支持一键导入 Clash 配置', '提供深色/浅色主题切换', '可配置自动测速和延迟检测', '建议开启服务模式以获得系统级代理']
    }
  },
  {
    id: 'clash-for-windows',
    name: 'Clash for Windows',
    icon: 'CFW',
    developer: 'Fndroid',
    platforms: ['windows'],
    core: 'Clash',
    codeStatus: '开源',
    price: '免费',
    featured: 'Win经典',
    tags: ['Clash', '开源', '免费', 'Win'],
    description: 'Windows 平台最受欢迎的 Clash 客户端（已停止更新），功能完善。',
    downloadUrl: 'https://github.com/Fndroid/clash_for_windows_pkg/releases',
    version: '0.20.39',
    updated: '2023年11月2日'
  },
  {
    id: 'clash-nyanpasu',
    name: 'Clash Nyanpasu',
    icon: 'CN',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/957b9f7918fc62e7a2ed0ce1ad43150c.webp',
    developer: 'LibNyanpasu',
    platforms: ['windows', 'mac', 'linux'],
    core: 'Mihomo',
    codeStatus: '开源',
    price: '免费',
    featured: '现代UI',
    tags: ['Mihomo', '开源', '免费', 'Win', 'Mac'],
    description: '基于 Tauri 的 Clash 图形客户端，界面现代，支持多种主题和自定义。',
    downloadUrl: 'https://github.com/LibNyanpasu/clash-nyanpasu/releases',
    version: '1.5.1',
    updated: '2026年9月19日',
    guide: {
      quickStart: '从官方渠道下载安装后，打开应用点击「+」或「添加配置」，粘贴订阅链接或导入配置文件，选择节点后点击连接按钮启用代理。',
      features: ['支持 Clash 规则集和策略组', '内置规则分流和 GeoIP 数据库', '实时流量统计和节点延迟测试', '完全开源，代码透明可审计', '跨平台支持，配置可同步'],
      tips: ['建议启用自动更新订阅，保持节点列表最新', '可以通过策略组实现自动选择最优节点', '定期测速以获得最佳连接体验', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', '首次使用需要在系统设置中允许添加 VPN 配置']
    }
  },
  {
    id: 'nekoray',
    name: 'NekoRay',
    icon: 'NR',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/fe77cebdbc2550430b638b36137f95b0.webp',
    developer: 'MatsuriDayo',
    platforms: ['windows', 'linux'],
    core: 'sing-box',
    codeStatus: '开源',
    price: '免费',
    featured: 'Qt界面',
    tags: ['sing-box', '开源', '免费', 'Win', 'Linux'],
    description: '基于 Qt 的跨平台代理客户端，支持 sing-box 和 Xray 核心。',
    downloadUrl: 'https://github.com/MatsuriDayo/nekoray/releases',
    version: '4.0-beta3',
    updated: '2026年9月13日',
    guide: {
      quickStart: '下载安装应用，打开后添加配置或订阅链接，选择节点并启用代理模式即可开始使用。',
      features: ['支持最新协议（Reality/Hysteria2/TUIC）', '高性能通用代理平台', '完整的规则路由系统', '完全开源，代码透明可审计'],
      tips: ['支持最新的 Reality 协议，隐蔽性更强', '可以配置规则集实现精准分流', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版']
    }
  },
  {
    id: 'invisible-man-xray',
    name: 'Invisible Man - Xray',
    icon: 'IM',
    developer: 'InvisibleManVPN',
    platforms: ['windows'],
    core: 'Xray',
    codeStatus: '开源',
    price: '免费',
    featured: 'GUI简洁',
    tags: ['Xray', '开源', '免费', 'Win'],
    description: 'Windows 平台简洁的 Xray 图形客户端，适合新手使用。',
    downloadUrl: 'https://github.com/InvisibleManVPN/InvisibleMan-XRayClient/releases',
    version: '0.9.5',
    updated: '2026年8月30日',
    guide: {
      quickStart: '下载解压后运行程序，点击「订阅」→「订阅设置」添加订阅地址，更新订阅后选择服务器节点，启用系统代理即可使用。',
      features: ['支持 VMess/VLESS/Trojan 等多种协议', '灵活的路由规则配置', '多种传输方式（TCP/WebSocket/gRPC）', '完全开源，代码透明可审计'],
      tips: ['建议优先使用 WebSocket+TLS 传输以获得更好的稳定性', '可以配置多个服务器作为备用', '路由规则可以实现国内外分流', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版']
    }
  },

  // === macOS 应用 ===
  {
    id: 'clashx-pro',
    name: 'ClashX Pro',
    icon: 'CX',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/5d37960ef33b0d47876e7bdc4c464a78.webp',
    developer: 'yichengchen',
    platforms: ['mac'],
    core: 'Clash Premium',
    codeStatus: '开源',
    price: '免费',
    featured: 'Mac经典',
    tags: ['Clash', '开源', '免费', 'Mac'],
    description: 'macOS 平台经典的 Clash 客户端，菜单栏设计，支持 TUN 模式和规则分流。',
    downloadUrl: 'https://github.com/yichengchen/clashX/releases',
    version: '1.118.0',
    updated: '2026年7月15日',
    guide: {
      quickStart: '从官方渠道下载安装后，打开应用点击「+」或「添加配置」，粘贴订阅链接或导入配置文件，选择节点后点击连接按钮启用代理。',
      features: ['完全开源，代码透明可审计'],
      tips: ['遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', '首次使用需要在系统设置中允许添加 VPN 配置']
    }
  },
  {
    id: 'v2rayu',
    name: 'V2RayU',
    icon: 'V2U',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/50579fb761217d43f6ec0c30b417da1f.webp',
    developer: 'yanue',
    platforms: ['mac'],
    core: 'V2Ray',
    codeStatus: '开源',
    price: '免费',
    featured: '菜单栏',
    tags: ['V2Ray', '开源', '免费', 'Mac'],
    description: 'macOS 平台 V2Ray 客户端，菜单栏设计，支持订阅和PAC模式。',
    downloadUrl: 'https://github.com/yanue/V2rayU/releases',
    version: '4.2.0',
    updated: '2026年8月20日',
    guide: {
      quickStart: '从官方渠道下载安装后，打开应用点击「+」或「添加配置」，粘贴订阅链接或导入配置文件，选择节点后点击连接按钮启用代理。',
      features: ['支持 VMess/VLESS/Trojan 等多种协议', '灵活的路由规则配置', '多种传输方式（TCP/WebSocket/gRPC）', '完全开源，代码透明可审计'],
      tips: ['建议优先使用 WebSocket+TLS 传输以获得更好的稳定性', '可以配置多个服务器作为备用', '路由规则可以实现国内外分流', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', '首次使用需要在系统设置中允许添加 VPN 配置']
    }
  },
  {
    id: 'qv2ray',
    name: 'Qv2ray',
    icon: 'Q2',
    developer: 'Qv2ray',
    platforms: ['windows', 'mac', 'linux'],
    core: 'V2Ray',
    codeStatus: '开源',
    price: '免费',
    featured: '跨平台',
    tags: ['V2Ray', '开源', '免费', 'Win', 'Mac', 'Linux'],
    description: '跨平台 V2Ray 图形客户端（已停止更新），功能完整，支持插件系统。',
    downloadUrl: 'https://github.com/Qv2ray/Qv2ray/releases',
    version: '2.7.0',
    updated: '2021年8月17日',
    guide: {
      quickStart: '从官方渠道下载安装后，打开应用点击「+」或「添加配置」，粘贴订阅链接或导入配置文件，选择节点后点击连接按钮启用代理。',
      features: ['支持 VMess/VLESS/Trojan 等多种协议', '灵活的路由规则配置', '多种传输方式（TCP/WebSocket/gRPC）', '完全开源，代码透明可审计', '跨平台支持，配置可同步'],
      tips: ['建议优先使用 WebSocket+TLS 传输以获得更好的稳定性', '可以配置多个服务器作为备用', '路由规则可以实现国内外分流', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', '首次使用需要在系统设置中允许添加 VPN 配置']
    }
  },

  // === Linux 应用 ===
  {
    id: 'v2raya',
    name: 'v2rayA',
    icon: 'V2A',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/b46dc93557947f3e2a05729305e25b25.webp',
    developer: 'v2rayA',
    platforms: ['linux', 'windows', 'mac'],
    core: 'V2Ray',
    codeStatus: '开源',
    price: '免费',
    featured: 'Web界面',
    tags: ['V2Ray', '开源', '免费', 'Linux', 'Web'],
    description: 'Linux 优先的 V2Ray Web 客户端，支持透明代理和全局代理。',
    downloadUrl: 'https://github.com/v2rayA/v2rayA/releases',
    version: '2.2.5.8',
    updated: '2026年9月17日',
    guide: {
      quickStart: '从官方渠道下载安装后，打开应用点击「+」或「添加配置」，粘贴订阅链接或导入配置文件，选择节点后点击连接按钮启用代理。',
      features: ['支持 VMess/VLESS/Trojan 等多种协议', '灵活的路由规则配置', '多种传输方式（TCP/WebSocket/gRPC）', '完全开源，代码透明可审计', '跨平台支持，配置可同步'],
      tips: ['建议优先使用 WebSocket+TLS 传输以获得更好的稳定性', '可以配置多个服务器作为备用', '路由规则可以实现国内外分流', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', '首次使用需要在系统设置中允许添加 VPN 配置']
    }
  },
  {
    id: 'clash-for-linux',
    name: 'Clash For Linux',
    icon: 'CFL',
    developer: 'Elegycloud',
    platforms: ['linux'],
    core: 'Clash',
    codeStatus: '开源',
    price: '免费',
    featured: 'Linux专用',
    tags: ['Clash', '开源', '免费', 'Linux'],
    description: 'Linux 平台的 Clash 图形客户端，基于 Electron，支持系统托盘。',
    downloadUrl: 'https://github.com/Elegycloud/clash-for-linux-backup/releases',
    version: '0.1.12',
    updated: '2023年9月8日',
    guide: {
      quickStart: '下载对应平台的安装包并安装，启动后点击「订阅」→「新建」，粘贴订阅地址并保存，然后在主界面选择节点并开启系统代理。',
      features: ['支持 Clash 规则集和策略组', '内置规则分流和 GeoIP 数据库', '实时流量统计和节点延迟测试', '完全开源，代码透明可审计'],
      tips: ['建议启用自动更新订阅，保持节点列表最新', '可以通过策略组实现自动选择最优节点', '定期测速以获得最佳连接体验', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版']
    }
  },

  // === 跨平台应用 ===
  {
    id: 'ficlash',
    name: 'FiClash',
    icon: 'FC',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/841d1900add91167b39e2fbd271c2563.webp',
    developer: 'chen08209',
    platforms: ['android', 'windows', 'mac', 'linux'],
    core: 'Mihomo',
    codeStatus: '开源',
    price: '免费',
    featured: '跨平台',
    tags: ['Mihomo', '开源', '免费', 'Android', 'Win', 'Mac'],
    description: '基于 Flutter 的 Mihomo 跨平台客户端，支持 WebDAV 同步和主题切换。',
    downloadUrl: 'https://github.com/chen08209/FlClash/releases',
    version: '0.8.72',
    updated: '2026年9月20日',
    guide: {
      quickStart: '从官方渠道下载安装后，打开应用点击「+」或「添加配置」，粘贴订阅链接或导入配置文件，选择节点后点击连接按钮启用代理。',
      features: ['支持 Clash 规则集和策略组', '内置规则分流和 GeoIP 数据库', '实时流量统计和节点延迟测试', '完全开源，代码透明可审计', '跨平台支持，配置可同步'],
      tips: ['建议启用自动更新订阅，保持节点列表最新', '可以通过策略组实现自动选择最优节点', '定期测速以获得最佳连接体验', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', '首次使用需要在系统设置中允许添加 VPN 配置', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'karing',
    name: 'Karing',
    icon: 'KR',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/fe26f8581b1a08d0f53d6c8f76f228fc.webp',
    developer: 'KaringX',
    platforms: ['android', 'ios', 'windows', 'mac', 'linux'],
    core: 'sing-box',
    codeStatus: '开源',
    price: '免费',
    featured: '简单易用',
    tags: ['sing-box', '开源', '免费', '全平台'],
    description: '简单强大的跨平台代理工具，基于 sing-box，支持多种配置格式。',
    downloadUrl: 'https://github.com/KaringX/karing/releases',
    version: '1.0.28.398',
    updated: '2026年9月19日',
    guide: {
      quickStart: '从官方渠道下载安装后，打开应用点击「+」或「添加配置」，粘贴订阅链接或导入配置文件，选择节点后点击连接按钮启用代理。',
      features: ['支持最新协议（Reality/Hysteria2/TUIC）', '高性能通用代理平台', '完整的规则路由系统', '完全开源，代码透明可审计', '跨平台支持，配置可同步'],
      tips: ['支持最新的 Reality 协议，隐蔽性更强', '可以配置规则集实现精准分流', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', '首次使用需要在系统设置中允许添加 VPN 配置', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'hiddify',
    name: 'Hiddify',
    icon: 'HD',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/892748ad0164b20434c62dae96dab6fa.webp',
    developer: 'Hiddify',
    platforms: ['android', 'ios', 'windows', 'mac', 'linux'],
    core: 'sing-box',
    codeStatus: '开源',
    price: '免费',
    featured: '多协议',
    tags: ['sing-box', '开源', '免费', '全平台'],
    description: '基于 sing-box 的多平台客户端，支持 Reality、Hysteria2 等新协议。',
    downloadUrl: 'https://github.com/hiddify/hiddify-next/releases',
    version: '2.0.5',
    updated: '2026年9月16日',
    guide: {
      quickStart: '从官方渠道下载安装后，打开应用点击「+」或「添加配置」，粘贴订阅链接或导入配置文件，选择节点后点击连接按钮启用代理。',
      features: ['支持最新协议（Reality/Hysteria2/TUIC）', '高性能通用代理平台', '完整的规则路由系统', '完全开源，代码透明可审计', '跨平台支持，配置可同步'],
      tips: ['支持最新的 Reality 协议，隐蔽性更强', '可以配置规则集实现精准分流', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', '首次使用需要在系统设置中允许添加 VPN 配置', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'sing-box',
    name: 'sing-box',
    icon: 'SB',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/af1e844cc280d8af141208ccd44a281e.webp',
    developer: 'SagerNet',
    platforms: ['android', 'ios', 'windows', 'mac', 'linux', 'openwrt'],
    core: 'sing-box',
    codeStatus: '开源',
    price: '免费',
    featured: '全平台',
    tags: ['sing-box', '开源', '免费', '命令行'],
    description: '通用代理平台，支持多种协议，可作为客户端或服务端使用。',
    downloadUrl: 'https://github.com/SagerNet/sing-box/releases',
    version: '1.9.5',
    updated: '2026年9月17日',
    guide: {
      quickStart: '从官方渠道下载安装后，打开应用点击「+」或「添加配置」，粘贴订阅链接或导入配置文件，选择节点后点击连接按钮启用代理。',
      features: ['支持最新协议（Reality/Hysteria2/TUIC）', '高性能通用代理平台', '完整的规则路由系统', '完全开源，代码透明可审计', '跨平台支持，配置可同步'],
      tips: ['支持最新的 Reality 协议，隐蔽性更强', '可以配置规则集实现精准分流', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', '首次使用需要在系统设置中允许添加 VPN 配置', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },

  // === HarmonyOS 应用 ===
  {
    id: 'clash-meta-harmony',
    name: 'Clash Meta for HarmonyOS',
    icon: 'CMH',
    developer: 'MetaCubeX',
    platforms: ['harmonyos'],
    core: 'Mihomo',
    codeStatus: '开源',
    price: '免费',
    featured: '鸿蒙专属',
    tags: ['Mihomo', '开源', '免费', 'HarmonyOS'],
    description: 'HarmonyOS 平台的 Clash Meta 客户端，原生支持鸿蒙系统。',
    downloadUrl: 'https://github.com/MetaCubeX/ClashMetaForAndroid/releases',
    version: '2.10.0-harmony',
    updated: '2026年8月18日',
    guide: {
      quickStart: '从官方渠道下载 HarmonyOS 版本安装包，安装后打开应用添加订阅或配置文件，选择节点后启用连接即可使用。',
      features: ['支持 Clash 规则集和策略组', '内置规则分流和 GeoIP 数据库', '实时流量统计和节点延迟测试', '完全开源，代码透明可审计'],
      tips: ['建议启用自动更新订阅，保持节点列表最新', '可以通过策略组实现自动选择最优节点', '定期测速以获得最佳连接体验', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版']
    }
  },
  {
    id: 'v2rayng-harmony',
    name: 'v2rayNG for HarmonyOS',
    icon: 'V2H',
    developer: '2dust',
    platforms: ['harmonyos'],
    core: 'Xray',
    codeStatus: '开源',
    price: '免费',
    featured: '鸿蒙版',
    tags: ['Xray', '开源', '免费', 'HarmonyOS'],
    description: 'v2rayNG 的 HarmonyOS 版本，支持鸿蒙原生特性。',
    downloadUrl: 'https://github.com/2dust/v2rayNG/releases',
    version: '1.9.5-harmony',
    updated: '2026年9月1日',
    guide: {
      quickStart: '从官方渠道下载 HarmonyOS 版本安装包，安装后打开应用添加订阅或配置文件，选择节点后启用连接即可使用。',
      features: ['支持 VMess/VLESS/Trojan 等多种协议', '灵活的路由规则配置', '多种传输方式（TCP/WebSocket/gRPC）', '完全开源，代码透明可审计'],
      tips: ['建议优先使用 WebSocket+TLS 传输以获得更好的稳定性', '可以配置多个服务器作为备用', '路由规则可以实现国内外分流', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版']
    }
  },
  {
    id: 'karing-harmony',
    name: 'Karing Harmony HAP',
    icon: 'KH',
    developer: 'KaringX',
    platforms: ['harmonyos'],
    core: 'sing-box',
    codeStatus: '未公开',
    price: '免费',
    featured: '鸿蒙推荐',
    tags: ['sing-box', '未公开', '免费', 'HarmonyOS'],
    description: '使用 KaringX/sing-box 源生内核的第三方 HarmonyOS 客户端，支持自省订阅、Clash 与内核协议转换。',
    downloadUrl: 'https://github.com/KaringX/karing/releases',
    version: '1.0.29.398',
    updated: '2026年9月15日',
    guide: {
      quickStart: '从官方渠道下载 HarmonyOS 版本安装包，安装后打开应用添加订阅或配置文件，选择节点后启用连接即可使用。',
      features: ['支持最新协议（Reality/Hysteria2/TUIC）', '高性能通用代理平台', '完整的规则路由系统'],
      tips: ['支持最新的 Reality 协议，隐蔽性更强', '可以配置规则集实现精准分流', '应用完全免费，请从官方渠道下载避免使用修改版']
    }
  },
  {
    id: 'clashbox-harmony',
    name: 'ClashBox',
    icon: 'CB',
    developer: 'ClashNEXT',
    platforms: ['harmonyos'],
    core: 'Mihomo',
    codeStatus: '源码不完整',
    price: '免费',
    featured: '鸿蒙自营销',
    tags: ['Mihomo', '源码不完整', '免费', 'HarmonyOS'],
    description: '专为 HarmonyOS NEXT 开发的原生代客户端，采用 Surfboard 风格界面，集成修改版 Mihomo 核心。',
    downloadUrl: 'https://github.com/ClashNEXT/ClashBox/releases',
    version: '1.2.0',
    updated: '2026年9月10日',
    guide: {
      quickStart: '从官方渠道下载 HarmonyOS 版本安装包，安装后打开应用添加订阅或配置文件，选择节点后启用连接即可使用。',
      features: ['支持 Clash 规则集和策略组', '内置规则分流和 GeoIP 数据库', '实时流量统计和节点延迟测试'],
      tips: ['建议启用自动更新订阅，保持节点列表最新', '可以通过策略组实现自动选择最优节点', '定期测速以获得最佳连接体验', '应用完全免费，请从官方渠道下载避免使用修改版']
    }
  },
  {
    id: 'ficlash-harmony',
    name: 'FiClash OpenHarmony',
    icon: 'FCH',
    developer: 'FiClash-ohos',
    platforms: ['harmonyos'],
    core: 'Mihomo',
    codeStatus: '开源',
    price: '免费',
    featured: '鸿蒙跨平台',
    tags: ['Mihomo', '开源', '免费', 'HarmonyOS'],
    description: 'FiClash 的 OpenHarmony 原生适配版，基于 Mihomo 的 tijk/Clash.Meta 分支，支持规则订阅管理。',
    downloadUrl: 'https://github.com/chen08209/FlClash/releases',
    version: '0.8.70',
    updated: '2026年9月8日',
    guide: {
      quickStart: '从官方渠道下载 HarmonyOS 版本安装包，安装后打开应用添加订阅或配置文件，选择节点后启用连接即可使用。',
      features: ['支持 Clash 规则集和策略组', '内置规则分流和 GeoIP 数据库', '实时流量统计和节点延迟测试', '完全开源，代码透明可审计'],
      tips: ['建议启用自动更新订阅，保持节点列表最新', '可以通过策略组实现自动选择最优节点', '定期测速以获得最佳连接体验', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版']
    }
  },
  {
    id: 'nekobox-harmony',
    name: 'NekoBox for Harmony',
    icon: 'NBH',
    developer: 'NekoBox4Harmony',
    platforms: ['harmonyos'],
    core: 'sing-box',
    codeStatus: '开源',
    price: '免费',
    featured: '鸿蒙原生',
    tags: ['sing-box', '开源', '免费', 'HarmonyOS'],
    description: '基于 sing-box 的 HarmonyOS NEXT 原生客户端，支持自省省点与订阅，Clash YAML 导入、规则自动管理等入。',
    downloadUrl: 'https://github.com/NekoBox4Harmony/NekoBox/releases',
    version: '1.1.5',
    updated: '2026年9月5日',
    guide: {
      quickStart: '从官方渠道下载 HarmonyOS 版本安装包，安装后打开应用添加订阅或配置文件，选择节点后启用连接即可使用。',
      features: ['支持最新协议（Reality/Hysteria2/TUIC）', '高性能通用代理平台', '完整的规则路由系统', '完全开源，代码透明可审计'],
      tips: ['支持最新的 Reality 协议，隐蔽性更强', '可以配置规则集实现精准分流', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版']
    }
  },
  {
    id: 'hey-harmony',
    name: 'Hey',
    icon: 'HY',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/a9014465b7b797c2df91f1e39097ea11.webp',
    developer: 'mMConnectTeam',
    platforms: ['harmonyos'],
    core: '多内核',
    codeStatus: '开源',
    price: '免费',
    featured: '鸿蒙位置',
    tags: ['多内核', '开源', '免费', 'HarmonyOS'],
    description: '基于 ArkTS 开发的 HarmonyOS NEXT 开源鸿蒙路由器和与协议汉语工具，支持 Xray 与 sing-box 核心、规则管理与自动订阅。',
    downloadUrl: 'https://github.com/mMConnectTeam/Hey/releases',
    version: '1.0.8',
    updated: '2026年9月3日',
    guide: {
      quickStart: '从官方渠道下载 HarmonyOS 版本安装包，安装后打开应用添加订阅或配置文件，选择节点后启用连接即可使用。',
      features: ['完全开源，代码透明可审计'],
      tips: ['遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版']
    }
  },
  {
    id: 'paws-harmony',
    name: 'Paws',
    icon: 'PW',
    developer: 'Paws for HarmonyOS',
    platforms: ['harmonyos'],
    core: 'meow-rs',
    codeStatus: '开源',
    price: '免费',
    featured: '鸿蒙轻量',
    tags: ['meow-rs', '开源', '免费', 'HarmonyOS'],
    description: '基于 meow-rs 与原生 ArkUI 界面的开源鸿蒙代理客户端，支持 Clash 配置与订阅导入、规则分流等。',
    downloadUrl: 'https://github.com/PawsForHarmonyOS/Paws/releases',
    version: '0.5.2',
    updated: '2026年8月28日',
    guide: {
      quickStart: '从官方渠道下载 HarmonyOS 版本安装包，安装后打开应用添加订阅或配置文件，选择节点后启用连接即可使用。',
      features: ['完全开源，代码透明可审计'],
      tips: ['遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版']
    }
  },

  // === OpenWrt / 路由器应用 ===
  {
    id: 'passwall',
    name: 'PassWall',
    icon: 'PW',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/9c2fb23e7ee30de6298a07e652338fb5.webp',
    developer: 'xiaorouji',
    platforms: ['openwrt'],
    core: 'Xray',
    codeStatus: '开源',
    price: '免费',
    featured: '路由器',
    tags: ['Xray', '开源', '免费', 'OpenWrt'],
    description: 'OpenWrt 平台强大的科学上网插件，支持多种协议和透明代理。',
    downloadUrl: 'https://github.com/xiaorouji/openwrt-passwall/releases',
    version: '4.76-1',
    updated: '2026年9月16日',
    guide: {
      quickStart: '在路由器管理界面的插件中心安装，进入插件配置页面，添加订阅地址或节点信息，启用服务并配置运行模式（全局/绕过大陆）。',
      features: ['支持 VMess/VLESS/Trojan 等多种协议', '灵活的路由规则配置', '多种传输方式（TCP/WebSocket/gRPC）', '完全开源，代码透明可审计'],
      tips: ['建议优先使用 WebSocket+TLS 传输以获得更好的稳定性', '可以配置多个服务器作为备用', '路由规则可以实现国内外分流', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版']
    }
  },
  {
    id: 'passwall2',
    name: 'PassWall 2',
    icon: 'PW2',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/cbc92255515823cbb64e84ba91f69968.webp',
    developer: 'xiaorouji',
    platforms: ['openwrt'],
    core: 'sing-box',
    codeStatus: '开源',
    price: '免费',
    featured: '新版本',
    tags: ['sing-box', '开源', '免费', 'OpenWrt'],
    description: 'PassWall 第二代，基于 sing-box，性能更优，功能更强。',
    downloadUrl: 'https://github.com/xiaorouji/openwrt-passwall2/releases',
    version: '1.20-4',
    updated: '2026年9月18日',
    guide: {
      quickStart: '在路由器管理界面的插件中心安装，进入插件配置页面，添加订阅地址或节点信息，启用服务并配置运行模式（全局/绕过大陆）。',
      features: ['支持最新协议（Reality/Hysteria2/TUIC）', '高性能通用代理平台', '完整的规则路由系统', '完全开源，代码透明可审计'],
      tips: ['支持最新的 Reality 协议，隐蔽性更强', '可以配置规则集实现精准分流', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版']
    }
  },
  {
    id: 'openclash',
    name: 'OpenClash',
    icon: 'OC',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/ff9415343d702b9e651ec8424988c0e8.webp',
    developer: 'vernesong',
    platforms: ['openwrt'],
    core: 'Clash',
    codeStatus: '开源',
    price: '免费',
    featured: 'Clash路由',
    tags: ['Clash', '开源', '免费', 'OpenWrt'],
    description: 'OpenWrt 平台的 Clash 客户端，支持规则管理和可视化配置。',
    downloadUrl: 'https://github.com/vernesong/OpenClash/releases',
    version: '0.46.028',
    updated: '2026年9月14日',
    guide: {
      quickStart: '在路由器管理界面的插件中心安装，进入插件配置页面，添加订阅地址或节点信息，启用服务并配置运行模式（全局/绕过大陆）。',
      features: ['支持 Clash 规则集和策略组', '内置规则分流和 GeoIP 数据库', '实时流量统计和节点延迟测试', '完全开源，代码透明可审计'],
      tips: ['建议启用自动更新订阅，保持节点列表最新', '可以通过策略组实现自动选择最优节点', '定期测速以获得最佳连接体验', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版']
    }
  },
  {
    id: 'shadowsocksr-plus',
    name: 'ShadowSocksR Plus+',
    icon: 'SSR',
    developer: 'fw876',
    platforms: ['openwrt'],
    core: 'SSR',
    codeStatus: '开源',
    price: '免费',
    featured: '经典',
    tags: ['SSR', '开源', '免费', 'OpenWrt'],
    description: 'OpenWrt 平台经典的 SSR 客户端，稳定可靠，配置简单。',
    downloadUrl: 'https://github.com/fw876/helloworld/releases',
    version: '2026.09.10',
    updated: '2026年9月10日',
    guide: {
      quickStart: '在路由器管理界面的插件中心安装，进入插件配置页面，添加订阅地址或节点信息，启用服务并配置运行模式（全局/绕过大陆）。',
      features: ['完全开源，代码透明可审计'],
      tips: ['遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版']
    }
  },
  {
    id: 'shellclash',
    name: 'ShellClash',
    icon: 'SC',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/857b176eea74abfe3f2ca0781301834c.webp',
    developer: 'juewuy',
    platforms: ['openwrt', 'router'],
    core: 'Clash',
    codeStatus: '开源',
    price: '免费',
    featured: 'Shell脚本',
    tags: ['Clash', '开源', '免费', 'OpenWrt', '路由器'],
    description: '基于 Shell 的 Clash 客户端，支持各种路由器系统，安装简便。',
    downloadUrl: 'https://github.com/juewuy/ShellClash/releases',
    version: '1.9.1',
    updated: '2026年9月15日',
    guide: {
      quickStart: '在路由器管理界面的插件中心安装，进入插件配置页面，添加订阅地址或节点信息，启用服务并配置运行模式（全局/绕过大陆）。',
      features: ['支持 Clash 规则集和策略组', '内置规则分流和 GeoIP 数据库', '实时流量统计和节点延迟测试', '完全开源，代码透明可审计'],
      tips: ['建议启用自动更新订阅，保持节点列表最新', '可以通过策略组实现自动选择最优节点', '定期测速以获得最佳连接体验', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版']
    }
  },

  // === 华硕/梅林路由器 ===
  {
    id: 'koolclash',
    name: 'KoolClash',
    icon: 'KC',
    developer: 'SaltedFish',
    platforms: ['router'],
    core: 'Clash',
    codeStatus: '开源',
    price: '免费',
    featured: '梅林固件',
    tags: ['Clash', '开源', '免费', '梅林'],
    description: '华硕/梅林路由器的 Clash 插件，界面友好，配置简单。',
    downloadUrl: 'https://github.com/SaltedFish0208/KoolClash/releases',
    version: '1.8.5',
    updated: '2023年10月5日',
    guide: {
      quickStart: '在路由器管理界面的插件中心安装，进入插件配置页面，添加订阅地址或节点信息，启用服务并配置运行模式（全局/绕过大陆）。',
      features: ['支持 Clash 规则集和策略组', '内置规则分流和 GeoIP 数据库', '实时流量统计和节点延迟测试', '完全开源，代码透明可审计'],
      tips: ['建议启用自动更新订阅，保持节点列表最新', '可以通过策略组实现自动选择最优节点', '定期测速以获得最佳连接体验', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版']
    }
  },
  {
    id: 'merlinclash',
    name: 'MerlinClash',
    icon: 'MC',
    developer: 'flyhigherpi',
    platforms: ['router'],
    core: 'Clash',
    codeStatus: '开源',
    price: '免费',
    featured: '梅林专用',
    tags: ['Clash', '开源', '免费', '梅林'],
    description: '梅林固件专用的 Clash 插件，功能完整，支持规则订阅。',
    downloadUrl: 'https://github.com/flyhigherpi/merlinclash/releases',
    version: '6.8.1',
    updated: '2026年9月8日',
    guide: {
      quickStart: '在路由器管理界面的插件中心安装，进入插件配置页面，添加订阅地址或节点信息，启用服务并配置运行模式（全局/绕过大陆）。',
      features: ['支持 Clash 规则集和策略组', '内置规则分流和 GeoIP 数据库', '实时流量统计和节点延迟测试', '完全开源，代码透明可审计'],
      tips: ['建议启用自动更新订阅，保持节点列表最新', '可以通过策略组实现自动选择最优节点', '定期测速以获得最佳连接体验', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版']
    }
  },

  // === 特殊平台 ===
  {
    id: 'clash-for-magisk',
    name: 'Clash For Magisk',
    icon: 'CFM',
    developer: 'taamarin',
    platforms: ['android'],
    core: 'Clash',
    codeStatus: '开源',
    price: '免费',
    featured: 'Magisk模块',
    tags: ['Clash', '开源', '免费', 'Magisk'],
    description: 'Android Magisk 模块形式的 Clash，无需独立应用，系统级代理。',
    downloadUrl: 'https://github.com/taamarin/box_for_magisk/releases',
    version: '1.1.8',
    updated: '2026年9月9日',
    guide: {
      quickStart: '安装后打开应用，点击「配置」→「新建配置」→「URL」，粘贴订阅链接并保存，返回主界面选择配置文件，点击连接按钮即可开始使用。',
      features: ['支持 Clash 规则集和策略组', '内置规则分流和 GeoIP 数据库', '实时流量统计和节点延迟测试', '完全开源，代码透明可审计'],
      tips: ['建议启用自动更新订阅，保持节点列表最新', '可以通过策略组实现自动选择最优节点', '定期测速以获得最佳连接体验', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'cloudflare-warp',
    name: 'Cloudflare WARP',
    icon: 'CF',
    developer: 'Cloudflare',
    platforms: ['windows', 'mac', 'linux', 'ios', 'android'],
    core: 'WireGuard',
    codeStatus: '未公开',
    price: '免费',
    featured: '官方工具',
    tags: ['WireGuard', '未公开', '免费', '全平台'],
    description: 'Cloudflare 官方 VPN 工具，基于 WireGuard，保护隐私和安全。',
    downloadUrl: 'https://1.1.1.1/',
    version: '2026.9.0',
    updated: '2026年9月1日',
    guide: {
      quickStart: '从官方渠道下载安装后，打开应用点击「+」或「添加配置」，粘贴订阅链接或导入配置文件，选择节点后点击连接按钮启用代理。',
      features: ['跨平台支持，配置可同步'],
      tips: ['应用完全免费，请从官方渠道下载避免使用修改版', '首次使用需要在系统设置中允许添加 VPN 配置', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  }
,

  // === 新增应用 ===
  {
    id: 'egern',
    name: 'Egern',
    icon: 'EG',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/33416caa568e56090f0b628734d69f96.webp',
    developer: 'Egern',
    platforms: ['ios'],
    core: '自研',
    codeStatus: '未公开',
    price: '付费',
    featured: '高级功能',
    tags: ['自研', '未公开', '$9.99', 'iOS'],
    description: 'iOS 平台高级网络工具，支持策略组、脚本和高级路由规则。',
    downloadUrl: 'https://apps.apple.com/app/egern/id1616105820',
    version: '2.5.0',
    updated: '2026年9月10日',
    guide: {
      quickStart: '在 App Store 购买并下载应用，首次打开时点击「添加配置」，选择「订阅」或「扫描二维码」导入节点，然后在主界面选择节点并开启连接。',
      features: ['原生性能优化，运行稳定流畅', '完善的规则配置和策略管理', '支持多种代理协议'],
      tips: ['请通过官方渠道购买以获得持续更新和支持', '首次使用需要在系统设置中允许添加 VPN 配置']
    }
  },
  {
    id: 'loon-lite',
    name: 'Loon Lite',
    icon: 'LL',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/353d3d6bc7f44a9ffe0d0be1bae7e782.webp',
    developer: 'Loon Network',
    platforms: ['ios'],
    core: '自研',
    codeStatus: '未公开',
    price: '免费',
    featured: '轻量版',
    tags: ['自研', '未公开', '免费', 'iOS'],
    description: 'Loon 的轻量版本，提供基础代理功能。',
    downloadUrl: 'https://apps.apple.com/app/loon-lite/id1628026956',
    version: '1.2.0',
    updated: '2026年8月15日',
    guide: {
      quickStart: '从官方渠道下载安装后，打开应用点击「+」或「添加配置」，粘贴订阅链接或导入配置文件，选择节点后点击连接按钮启用代理。',
      features: ['原生性能优化，运行稳定流畅', '完善的规则配置和策略管理', '支持多种代理协议'],
      tips: ['应用完全免费，请从官方渠道下载避免使用修改版', '首次使用需要在系统设置中允许添加 VPN 配置']
    }
  },
  {
    id: 'box-for-android',
    name: 'Box for Android',
    icon: 'BFA',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/be3b1d00b8bb02fc3a4d1d74f7442d41.webp',
    developer: 'SagerNet',
    platforms: ['android'],
    core: 'sing-box',
    codeStatus: '开源',
    price: '免费',
    featured: 'sing-box',
    tags: ['sing-box', '开源', '免费', 'Android'],
    description: 'Android 平台的 sing-box 图形客户端，支持多种协议。',
    downloadUrl: 'https://github.com/SagerNet/sing-box-for-android/releases',
    version: '1.8.0',
    updated: '2026年9月12日',
    guide: {
      quickStart: '安装应用后，点击「配置」→「添加」→「从 URL 导入」，输入订阅链接，选择配置文件后点击连接按钮启动代理。',
      features: ['支持最新协议（Reality/Hysteria2/TUIC）', '高性能通用代理平台', '完整的规则路由系统', '完全开源，代码透明可审计'],
      tips: ['支持最新的 Reality 协议，隐蔽性更强', '可以配置规则集实现精准分流', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'box-for-root',
    name: 'Box for Root',
    icon: 'BFR',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/95f7420e82bdf17623df7f8509684cf6.webp',
    developer: 'taamarin',
    platforms: ['android'],
    core: 'sing-box',
    codeStatus: '开源',
    price: '免费',
    featured: 'Root',
    tags: ['sing-box', '开源', '免费', 'Android', 'Root'],
    description: 'Android Root 设备专用的 sing-box 客户端，支持透明代理。',
    downloadUrl: 'https://github.com/taamarin/box_for_magisk/releases',
    version: '1.2.5',
    updated: '2026年9月8日',
    guide: {
      quickStart: '安装应用后，点击「配置」→「添加」→「从 URL 导入」，输入订阅链接，选择配置文件后点击连接按钮启动代理。',
      features: ['支持最新协议（Reality/Hysteria2/TUIC）', '高性能通用代理平台', '完整的规则路由系统', '完全开源，代码透明可审计'],
      tips: ['支持最新的 Reality 协议，隐蔽性更强', '可以配置规则集实现精准分流', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'clash-party',
    name: 'Clash Party',
    icon: 'CPT',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/ce7a8dcab6515bd03eca2c89b6d46311.webp',
    developer: 'Clash Party',
    platforms: ['windows', 'mac', 'linux'],
    core: 'Mihomo',
    codeStatus: '开源',
    price: '免费',
    featured: '派对版',
    tags: ['Mihomo', '开源', '免费', 'Win', 'Mac', 'Linux'],
    description: '基于 Tauri 的 Mihomo 图形客户端，界面友好，功能丰富。',
    downloadUrl: 'https://github.com/clashparty/clash-party/releases',
    version: '1.2.0',
    updated: '2026年9月14日',
    guide: {
      quickStart: '从官方渠道下载安装后，打开应用点击「+」或「添加配置」，粘贴订阅链接或导入配置文件，选择节点后点击连接按钮启用代理。',
      features: ['支持 Clash 规则集和策略组', '内置规则分流和 GeoIP 数据库', '实时流量统计和节点延迟测试', '完全开源，代码透明可审计', '跨平台支持，配置可同步'],
      tips: ['建议启用自动更新订阅，保持节点列表最新', '可以通过策略组实现自动选择最优节点', '定期测速以获得最佳连接体验', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', '首次使用需要在系统设置中允许添加 VPN 配置']
    }
  },
  {
    id: 'gui-for-clash',
    name: 'GUI.for.Clash',
    icon: 'GFC',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/4849a936711e2f657645d1a12019872b.webp',
    developer: 'GUI.for.Clash',
    platforms: ['windows', 'mac', 'linux'],
    core: 'Mihomo',
    codeStatus: '开源',
    price: '免费',
    featured: 'Clash GUI',
    tags: ['Mihomo', '开源', '免费', 'Win', 'Mac', 'Linux'],
    description: '跨平台 Clash 图形界面，基于 Flutter，界面美观。',
    downloadUrl: 'https://github.com/GUI-for-Cores/GUI.for.Clash/releases',
    version: '1.5.8',
    updated: '2026年9月18日',
    guide: {
      quickStart: '从官方渠道下载安装后，打开应用点击「+」或「添加配置」，粘贴订阅链接或导入配置文件，选择节点后点击连接按钮启用代理。',
      features: ['支持 Clash 规则集和策略组', '内置规则分流和 GeoIP 数据库', '实时流量统计和节点延迟测试', '完全开源，代码透明可审计', '跨平台支持，配置可同步'],
      tips: ['建议启用自动更新订阅，保持节点列表最新', '可以通过策略组实现自动选择最优节点', '定期测速以获得最佳连接体验', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', '首次使用需要在系统设置中允许添加 VPN 配置']
    }
  },
  {
    id: 'gui-for-singbox',
    name: 'GUI.for.SingBox',
    icon: 'GFS',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/c9d341c7097ff6f7c26a33a408ce76ce.webp',
    developer: 'GUI.for.Cores',
    platforms: ['windows', 'mac', 'linux'],
    core: 'sing-box',
    codeStatus: '开源',
    price: '免费',
    featured: 'SingBox GUI',
    tags: ['sing-box', '开源', '免费', 'Win', 'Mac', 'Linux'],
    description: '跨平台 sing-box 图形界面，基于 Flutter，支持多种协议。',
    downloadUrl: 'https://github.com/GUI-for-Cores/GUI.for.SingBox/releases',
    version: '1.3.2',
    updated: '2026年9月16日',
    guide: {
      quickStart: '从官方渠道下载安装后，打开应用点击「+」或「添加配置」，粘贴订阅链接或导入配置文件，选择节点后点击连接按钮启用代理。',
      features: ['支持最新协议（Reality/Hysteria2/TUIC）', '高性能通用代理平台', '完整的规则路由系统', '完全开源，代码透明可审计', '跨平台支持，配置可同步'],
      tips: ['支持最新的 Reality 协议，隐蔽性更强', '可以配置规则集实现精准分流', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', '首次使用需要在系统设置中允许添加 VPN 配置']
    }
  },
  {
    id: 'netch',
    name: 'Netch',
    icon: 'NET',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/90b633a3f08492e35bf62476b392c22f.webp',
    developer: 'NetchX',
    platforms: ['windows'],
    core: '多核心',
    codeStatus: '开源',
    price: '免费',
    featured: '游戏加速',
    tags: ['多核心', '开源', '免费', 'Win'],
    description: 'Windows 游戏加速工具，支持多种代理协议和进程模式。',
    downloadUrl: 'https://github.com/netchx/netch/releases',
    version: '1.9.7',
    updated: '2026年8月25日',
    guide: {
      quickStart: '下载安装应用，打开后添加配置或订阅链接，选择节点并启用代理模式即可开始使用。',
      features: ['完全开源，代码透明可审计'],
      tips: ['遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版']
    }
  },
  {
    id: 'daed',
    name: 'daed',
    icon: 'DAE',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/977c2a4d0d1ebf65c4dd2e2af4a80d20.webp',
    developer: 'daeuniverse',
    platforms: ['linux', 'windows', 'mac'],
    core: 'dae',
    codeStatus: '开源',
    price: '免费',
    featured: 'Web管理',
    tags: ['dae', '开源', '免费', 'Linux'],
    description: 'dae 的 Web 管理面板，支持图形化配置和管理。',
    downloadUrl: 'https://github.com/daeuniverse/daed/releases',
    version: '0.7.0',
    updated: '2026年9月10日',
    guide: {
      quickStart: '从官方渠道下载安装后，打开应用点击「+」或「添加配置」，粘贴订阅链接或导入配置文件，选择节点后点击连接按钮启用代理。',
      features: ['完全开源，代码透明可审计', '跨平台支持，配置可同步'],
      tips: ['遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', '首次使用需要在系统设置中允许添加 VPN 配置']
    }
  },
  {
    id: 'homeproxy',
    name: 'HomeProxy',
    icon: 'HP',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/9e70d44f13080b7cc311f56b3b110a8e.webp',
    developer: 'immortalwrt',
    platforms: ['openwrt'],
    core: 'sing-box',
    codeStatus: '开源',
    price: '免费',
    featured: '家庭代理',
    tags: ['sing-box', '开源', '免费', 'OpenWrt'],
    description: 'OpenWrt 家庭代理解决方案，基于 sing-box，配置简单。',
    downloadUrl: 'https://github.com/immortalwrt/homeproxy/releases',
    version: '2024.09.10',
    updated: '2026年9月10日',
    guide: {
      quickStart: '在路由器管理界面的插件中心安装，进入插件配置页面，添加订阅地址或节点信息，启用服务并配置运行模式（全局/绕过大陆）。',
      features: ['支持最新协议（Reality/Hysteria2/TUIC）', '高性能通用代理平台', '完整的规则路由系统', '完全开源，代码透明可审计'],
      tips: ['支持最新的 Reality 协议，隐蔽性更强', '可以配置规则集实现精准分流', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版']
    }
  },
  {
    id: 'fancyss',
    name: 'Fancyss',
    icon: 'FSS',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/10e61c19da1a26099fa527b188d417d5.webp',
    developer: 'hq450',
    platforms: ['router'],
    core: 'Xray',
    codeStatus: '开源',
    price: '免费',
    featured: '华硕路由',
    tags: ['Xray', '开源', '免费', '华硕', '梅林'],
    description: '华硕/梅林路由器科学上网插件，功能强大，配置友好。',
    downloadUrl: 'https://github.com/hq450/fancyss/releases',
    version: '3.0.5',
    updated: '2026年9月13日',
    guide: {
      quickStart: '在路由器管理界面的插件中心安装，进入插件配置页面，添加订阅地址或节点信息，启用服务并配置运行模式（全局/绕过大陆）。',
      features: ['支持 VMess/VLESS/Trojan 等多种协议', '灵活的路由规则配置', '多种传输方式（TCP/WebSocket/gRPC）', '完全开源，代码透明可审计'],
      tips: ['建议优先使用 WebSocket+TLS 传输以获得更好的稳定性', '可以配置多个服务器作为备用', '路由规则可以实现国内外分流', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版']
    }
  },
  {
    id: 'flclashx-harmony',
    name: 'FlClashX',
    icon: 'FCX',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/06e6ac2d83db5ea0553a0b56ccca2ca9.webp',
    developer: 'FlClash',
    platforms: ['harmonyos'],
    core: 'Mihomo',
    codeStatus: '开源',
    price: '免费',
    featured: '鸿蒙优化',
    tags: ['Mihomo', '开源', '免费', 'HarmonyOS'],
    description: 'HarmonyOS 原生 Clash 客户端，界面精美，性能优秀。',
    downloadUrl: 'https://github.com/chen08209/FlClash/releases',
    version: '0.8.75',
    updated: '2026年9月16日',
    guide: {
      quickStart: '从官方渠道下载 HarmonyOS 版本安装包，安装后打开应用添加订阅或配置文件，选择节点后启用连接即可使用。',
      features: ['支持 Clash 规则集和策略组', '内置规则分流和 GeoIP 数据库', '实时流量统计和节点延迟测试', '完全开源，代码透明可审计'],
      tips: ['建议启用自动更新订阅，保持节点列表最新', '可以通过策略组实现自动选择最优节点', '定期测速以获得最佳连接体验', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版']
    }
  },
  {
    id: 'insightbox',
    name: 'InsightBox',
    icon: 'IB',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/e6ddb2329f30ad1885833fef466faa08.webp',
    developer: 'InsightBox Team',
    platforms: ['harmonyos'],
    core: 'sing-box',
    codeStatus: '开源',
    price: '免费',
    featured: '鸿蒙新星',
    tags: ['sing-box', '开源', '免费', 'HarmonyOS'],
    description: 'HarmonyOS NEXT 原生代理客户端，基于 sing-box 核心。',
    downloadUrl: 'https://github.com/InsightBox/InsightBox/releases',
    version: '1.0.8',
    updated: '2026年9月12日',
    guide: {
      quickStart: '从官方渠道下载 HarmonyOS 版本安装包，安装后打开应用添加订阅或配置文件，选择节点后启用连接即可使用。',
      features: ['支持最新协议（Reality/Hysteria2/TUIC）', '高性能通用代理平台', '完整的规则路由系统', '完全开源，代码透明可审计'],
      tips: ['支持最新的 Reality 协议，隐蔽性更强', '可以配置规则集实现精准分流', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版']
    }
  },
  {
    id: 'anywhere',
    name: 'Anywhere',
    icon: 'AW',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/4b03a34ecc75fee426d5cb7226a3b3cb.webp',
    developer: 'Anywhere Team',
    platforms: ['windows', 'mac', 'linux', 'android'],
    core: 'sing-box',
    codeStatus: '开源',
    price: '免费',
    featured: '全平台',
    tags: ['sing-box', '开源', '免费', '全平台'],
    description: '跨平台代理工具，随时随地使用，界面简洁易用。',
    downloadUrl: 'https://github.com/Anywhere-App/Anywhere/releases',
    version: '1.2.0',
    updated: '2026年9月12日',
    guide: {
      quickStart: '从官方渠道下载安装后，打开应用点击「+」或「添加配置」，粘贴订阅链接或导入配置文件，选择节点后点击连接按钮启用代理。',
      features: ['支持最新协议（Reality/Hysteria2/TUIC）', '高性能通用代理平台', '完整的规则路由系统', '完全开源，代码透明可审计', '跨平台支持，配置可同步'],
      tips: ['支持最新的 Reality 协议，隐蔽性更强', '可以配置规则集实现精准分流', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', '首次使用需要在系统设置中允许添加 VPN 配置', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  }
,

  // === 补充应用（第二批）===
  {
    id: 'bettbox',
    name: 'BettBox',
    icon: 'BB',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/e206326d5b72551a67ac47541df06551.webp',
    developer: 'BettBox',
    platforms: ['windows', 'mac', 'linux', 'android'],
    core: 'sing-box',
    codeStatus: '开源',
    price: '免费',
    tags: ['sing-box', '开源', '免费', '全平台'],
    description: '跨平台 sing-box 图形客户端，简单易用，功能完整。',
    downloadUrl: 'https://github.com/BettBox/BettBox/releases',
    version: '1.1.5',
    updated: '2026年9月16日',
    guide: {
      quickStart: '从官方渠道下载安装后，打开应用点击「+」或「添加配置」，粘贴订阅链接或导入配置文件，选择节点后点击连接按钮启用代理。',
      features: ['支持最新协议（Reality/Hysteria2/TUIC）', '高性能通用代理平台', '完整的规则路由系统', '完全开源，代码透明可审计', '跨平台支持，配置可同步'],
      tips: ['支持最新的 Reality 协议，隐蔽性更强', '可以配置规则集实现精准分流', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', '首次使用需要在系统设置中允许添加 VPN 配置', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'flyclash',
    name: 'FlyClash',
    icon: 'FLC',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/d8b8d99fb7f73d1bda662d28d7284917.webp',
    developer: 'FlyClash',
    platforms: ['windows', 'mac', 'linux'],
    core: 'Mihomo',
    codeStatus: '开源',
    price: '免费',
    tags: ['Mihomo', '开源', '免费', 'Win', 'Mac'],
    description: '轻量级 Clash 桌面客户端，界面清爽，性能优秀。',
    downloadUrl: 'https://github.com/FlyClash/FlyClash/releases',
    version: '1.0.3',
    updated: '2026年9月14日',
    guide: {
      quickStart: '从官方渠道下载安装后，打开应用点击「+」或「添加配置」，粘贴订阅链接或导入配置文件，选择节点后点击连接按钮启用代理。',
      features: ['支持 Clash 规则集和策略组', '内置规则分流和 GeoIP 数据库', '实时流量统计和节点延迟测试', '完全开源，代码透明可审计', '跨平台支持，配置可同步'],
      tips: ['建议启用自动更新订阅，保持节点列表最新', '可以通过策略组实现自动选择最优节点', '定期测速以获得最佳连接体验', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', '首次使用需要在系统设置中允许添加 VPN 配置']
    }
  },
  {
    id: 'flyclash-android',
    name: 'FlyClash Android',
    icon: 'FLA',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/9de2b0e57210cbbe84d4083b723481e6.webp',
    developer: 'FlyClash',
    platforms: ['android'],
    core: 'Mihomo',
    codeStatus: '开源',
    price: '免费',
    tags: ['Mihomo', '开源', '免费', 'Android'],
    description: 'FlyClash 的 Android 版本，轻量快速。',
    downloadUrl: 'https://github.com/FlyClash/FlyClash-Android/releases',
    version: '1.0.2',
    updated: '2026年9月14日',
    guide: {
      quickStart: '安装后打开应用，点击「配置」→「新建配置」→「URL」，粘贴订阅链接并保存，返回主界面选择配置文件，点击连接按钮即可开始使用。',
      features: ['支持 Clash 规则集和策略组', '内置规则分流和 GeoIP 数据库', '实时流量统计和节点延迟测试', '完全开源，代码透明可审计'],
      tips: ['建议启用自动更新订阅，保持节点列表最新', '可以通过策略组实现自动选择最优节点', '定期测速以获得最佳连接体验', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'exclave',
    name: 'Exclave',
    icon: 'EXC',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/ddbb4d61bf160a06ee242a8139e66079.webp',
    developer: 'Exclave',
    platforms: ['ios', 'mac'],
    core: '自研',
    codeStatus: '未公开',
    price: '付费',
    tags: ['自研', '未公开', '$6.99', 'iOS', 'Mac'],
    description: 'iOS/Mac 高级网络工具，支持脚本和自动化规则。',
    downloadUrl: 'https://apps.apple.com/app/exclave/id1607037498',
    version: '2.3.0',
    updated: '2026年9月8日',
    guide: {
      quickStart: '在 App Store 购买并下载应用，首次打开时点击「添加配置」，选择「订阅」或「扫描二维码」导入节点，然后在主界面选择节点并开启连接。',
      features: ['原生性能优化，运行稳定流畅', '完善的规则配置和策略管理', '支持多种代理协议'],
      tips: ['请通过官方渠道购买以获得持续更新和支持', '首次使用需要在系统设置中允许添加 VPN 配置']
    }
  },
  {
    id: 'clashmac',
    name: 'ClashMac',
    icon: 'CM',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/ac494283455b4120eaf1e9270a64bd98.webp',
    developer: 'ClashMac',
    platforms: ['mac'],
    core: 'Clash',
    codeStatus: '开源',
    price: '免费',
    tags: ['Clash', '开源', '免费', 'Mac'],
    description: 'macOS 原生 Clash 客户端，菜单栏设计，轻量流畅。',
    downloadUrl: 'https://github.com/ClashMac/ClashMac/releases',
    version: '1.5.0',
    updated: '2026年9月2日',
    guide: {
      quickStart: '从官方渠道下载安装后，打开应用点击「+」或「添加配置」，粘贴订阅链接或导入配置文件，选择节点后点击连接按钮启用代理。',
      features: ['支持 Clash 规则集和策略组', '内置规则分流和 GeoIP 数据库', '实时流量统计和节点延迟测试', '完全开源，代码透明可审计'],
      tips: ['建议启用自动更新订阅，保持节点列表最新', '可以通过策略组实现自动选择最优节点', '定期测速以获得最佳连接体验', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', '首次使用需要在系统设置中允许添加 VPN 配置']
    }
  },
  {
    id: 'clashbar',
    name: 'ClashBar',
    icon: 'CB',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/5c17c72cd42017682be8018cef4cd6f4.webp',
    developer: 'ClashBar',
    platforms: ['mac'],
    core: 'Mihomo',
    codeStatus: '开源',
    price: '免费',
    tags: ['Mihomo', '开源', '免费', 'Mac'],
    description: 'macOS 菜单栏 Clash 客户端，简洁高效。',
    downloadUrl: 'https://github.com/ClashBar/ClashBar/releases',
    version: '1.2.3',
    updated: '2026年9月1日',
    guide: {
      quickStart: '从官方渠道下载安装后，打开应用点击「+」或「添加配置」，粘贴订阅链接或导入配置文件，选择节点后点击连接按钮启用代理。',
      features: ['支持 Clash 规则集和策略组', '内置规则分流和 GeoIP 数据库', '实时流量统计和节点延迟测试', '完全开源，代码透明可审计'],
      tips: ['建议启用自动更新订阅，保持节点列表最新', '可以通过策略组实现自动选择最优节点', '定期测速以获得最佳连接体验', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', '首次使用需要在系统设置中允许添加 VPN 配置']
    }
  },
  {
    id: 'clash-mi',
    name: 'Clash Mi',
    icon: 'CMI',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/202f6d8b6cc47907475b77bc8e582e15.webp',
    developer: 'Clash Mi',
    platforms: ['android'],
    core: 'Mihomo',
    codeStatus: '开源',
    price: '免费',
    tags: ['Mihomo', '开源', '免费', 'Android'],
    description: 'Android Mihomo 客户端，Material Design 界面。',
    downloadUrl: 'https://github.com/ClashMi/ClashMi/releases',
    version: '1.3.0',
    updated: '2026年8月28日',
    guide: {
      quickStart: '安装后打开应用，点击「配置」→「新建配置」→「URL」，粘贴订阅链接并保存，返回主界面选择配置文件，点击连接按钮即可开始使用。',
      features: ['支持 Clash 规则集和策略组', '内置规则分流和 GeoIP 数据库', '实时流量统计和节点延迟测试', '完全开源，代码透明可审计'],
      tips: ['建议启用自动更新订阅，保持节点列表最新', '可以通过策略组实现自动选择最优节点', '定期测速以获得最佳连接体验', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'clashn',
    name: 'ClashN',
    icon: 'CN',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/aa660d645e93de8ecded7bbc38393a76.webp',
    developer: 'ClashN',
    platforms: ['android'],
    core: 'Mihomo',
    codeStatus: '开源',
    price: '免费',
    tags: ['Mihomo', '开源', '免费', 'Android'],
    description: 'Android 平台新一代 Clash 客户端。',
    downloadUrl: 'https://github.com/ClashN/ClashN-Android/releases',
    version: '1.1.0',
    updated: '2026年8月20日',
    guide: {
      quickStart: '安装后打开应用，点击「配置」→「新建配置」→「URL」，粘贴订阅链接并保存，返回主界面选择配置文件，点击连接按钮即可开始使用。',
      features: ['支持 Clash 规则集和策略组', '内置规则分流和 GeoIP 数据库', '实时流量统计和节点延迟测试', '完全开源，代码透明可审计'],
      tips: ['建议启用自动更新订阅，保持节点列表最新', '可以通过策略组实现自动选择最优节点', '定期测速以获得最佳连接体验', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'connect-now',
    name: 'Connect Now',
    icon: 'CNW',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/c814d3f142d57dc3686da31f63d44de3.webp',
    developer: 'Connect Now',
    platforms: ['android', 'ios'],
    core: '自研',
    codeStatus: '未公开',
    price: '免费增值',
    tags: ['自研', '未公开', '免费增值', 'Android', 'iOS'],
    description: '快速连接工具，一键启动，界面友好。',
    downloadUrl: 'https://connectnow.app',
    version: '2.0.5',
    updated: '2026年9月5日',
    guide: {
      quickStart: '从官方渠道下载安装后，打开应用点击「+」或「添加配置」，粘贴订阅链接或导入配置文件，选择节点后点击连接按钮启用代理。',
      features: ['原生性能优化，运行稳定流畅', '完善的规则配置和策略管理', '支持多种代理协议'],
      tips: ['请通过官方渠道购买以获得持续更新和支持', '首次使用需要在系统设置中允许添加 VPN 配置', 'Android 7+ 需要在应用设置中授予必要的网络权限']
    }
  },
  {
    id: 'happ-proxy',
    name: 'Happ Proxy',
    icon: 'HAP',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/925261e78a7cc6e2c29e204ad2e6583e.webp',
    developer: 'Happ',
    platforms: ['ios'],
    core: 'sing-box',
    codeStatus: '未公开',
    price: '付费',
    tags: ['sing-box', '未公开', '$4.99', 'iOS'],
    description: 'iOS 平台代理工具，基于 sing-box，支持多种协议。',
    downloadUrl: 'https://apps.apple.com/app/happ-proxy/id1605739825',
    version: '1.8.0',
    updated: '2026年8月30日',
    guide: {
      quickStart: '在 App Store 购买并下载应用，首次打开时点击「添加配置」，选择「订阅」或「扫描二维码」导入节点，然后在主界面选择节点并开启连接。',
      features: ['支持最新协议（Reality/Hysteria2/TUIC）', '高性能通用代理平台', '完整的规则路由系统'],
      tips: ['支持最新的 Reality 协议，隐蔽性更强', '可以配置规则集实现精准分流', '请通过官方渠道购买以获得持续更新和支持', '首次使用需要在系统设置中允许添加 VPN 配置']
    }
  },
  {
    id: 'husi',
    name: 'Husi',
    icon: 'HSI',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/c3562e924c4cd6637cfcf0ef32069af0.webp',
    developer: 'Husi Team',
    platforms: ['harmonyos'],
    core: 'Mihomo',
    codeStatus: '开源',
    price: '免费',
    tags: ['Mihomo', '开源', '免费', 'HarmonyOS'],
    description: 'HarmonyOS NEXT 原生 Clash 客户端，界面美观。',
    downloadUrl: 'https://github.com/Husi/Husi/releases',
    version: '1.0.2',
    updated: '2026年8月25日',
    guide: {
      quickStart: '从官方渠道下载 HarmonyOS 版本安装包，安装后打开应用添加订阅或配置文件，选择节点后启用连接即可使用。',
      features: ['支持 Clash 规则集和策略组', '内置规则分流和 GeoIP 数据库', '实时流量统计和节点延迟测试', '完全开源，代码透明可审计'],
      tips: ['建议启用自动更新订阅，保持节点列表最新', '可以通过策略组实现自动选择最优节点', '定期测速以获得最佳连接体验', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版']
    }
  },
  {
    id: 'incy',
    name: 'Incy',
    icon: 'INC',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/17c21f8ee5969d639c1004b46ec38b97.webp',
    developer: 'Incy Team',
    platforms: ['harmonyos'],
    core: 'sing-box',
    codeStatus: '开源',
    price: '免费',
    tags: ['sing-box', '开源', '免费', 'HarmonyOS'],
    description: 'HarmonyOS 轻量级代理客户端，简单快速。',
    downloadUrl: 'https://github.com/Incy/Incy/releases',
    version: '0.9.5',
    updated: '2026年8月22日',
    guide: {
      quickStart: '从官方渠道下载 HarmonyOS 版本安装包，安装后打开应用添加订阅或配置文件，选择节点后启用连接即可使用。',
      features: ['支持最新协议（Reality/Hysteria2/TUIC）', '高性能通用代理平台', '完整的规则路由系统', '完全开源，代码透明可审计'],
      tips: ['支持最新的 Reality 协议，隐蔽性更强', '可以配置规则集实现精准分流', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版']
    }
  },
  {
    id: 'tomoon',
    name: 'ToMoon',
    icon: 'TM',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/be66f6aebe0bf2d97afbd2422da179b8.webp',
    developer: 'ToMoon',
    platforms: ['windows', 'mac'],
    core: 'Xray',
    codeStatus: '开源',
    price: '免费',
    tags: ['Xray', '开源', '免费', 'Win', 'Mac'],
    description: '桌面 Xray 客户端，界面精美，功能完善。',
    downloadUrl: 'https://github.com/ToMoon/ToMoon/releases',
    version: '1.4.0',
    updated: '2026年9月13日',
    guide: {
      quickStart: '从官方渠道下载安装后，打开应用点击「+」或「添加配置」，粘贴订阅链接或导入配置文件，选择节点后点击连接按钮启用代理。',
      features: ['支持 VMess/VLESS/Trojan 等多种协议', '灵活的路由规则配置', '多种传输方式（TCP/WebSocket/gRPC）', '完全开源，代码透明可审计'],
      tips: ['建议优先使用 WebSocket+TLS 传输以获得更好的稳定性', '可以配置多个服务器作为备用', '路由规则可以实现国内外分流', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', '首次使用需要在系统设置中允许添加 VPN 配置']
    }
  },
  {
    id: 'throne',
    name: 'Throne',
    icon: 'THR',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/6ac98da03a71afc2dff22f5dc892ac22.webp',
    developer: 'Throne',
    platforms: ['ios', 'mac'],
    core: '自研',
    codeStatus: '未公开',
    price: '付费',
    tags: ['自研', '未公开', '$8.99', 'iOS', 'Mac'],
    description: 'iOS/Mac 高级网络工具，企业级功能。',
    downloadUrl: 'https://apps.apple.com/app/throne/id1598473621',
    version: '2.1.0',
    updated: '2026年9月6日',
    guide: {
      quickStart: '在 App Store 购买并下载应用，首次打开时点击「添加配置」，选择「订阅」或「扫描二维码」导入节点，然后在主界面选择节点并开启连接。',
      features: ['原生性能优化，运行稳定流畅', '完善的规则配置和策略管理', '支持多种代理协议'],
      tips: ['请通过官方渠道购买以获得持续更新和支持', '首次使用需要在系统设置中允许添加 VPN 配置']
    }
  },
  {
    id: 'tunna',
    name: 'Tunna',
    icon: 'TUN',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/514c717bb3da918110ba53a518da900d.webp',
    developer: 'Tunna',
    platforms: ['windows', 'mac', 'linux'],
    core: 'WireGuard',
    codeStatus: '开源',
    price: '免费',
    tags: ['WireGuard', '开源', '免费', '全平台'],
    description: '跨平台 WireGuard 图形客户端，配置简单。',
    downloadUrl: 'https://github.com/Tunna/Tunna/releases',
    version: '1.5.2',
    updated: '2026年9月4日',
    guide: {
      quickStart: '从官方渠道下载安装后，打开应用点击「+」或「添加配置」，粘贴订阅链接或导入配置文件，选择节点后点击连接按钮启用代理。',
      features: ['完全开源，代码透明可审计', '跨平台支持，配置可同步'],
      tips: ['遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', '首次使用需要在系统设置中允许添加 VPN 配置']
    }
  },
  {
    id: 'pandora-box',
    name: 'Pandora Box',
    icon: 'PDB',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/37e740027bf6480d7ffde71b12ee6e54.webp',
    developer: 'Pandora',
    platforms: ['openwrt'],
    core: '多核心',
    codeStatus: '开源',
    price: '免费',
    tags: ['多核心', '开源', '免费', 'OpenWrt'],
    description: 'OpenWrt 多合一科学上网解决方案。',
    downloadUrl: 'https://github.com/PandoraBox/PandoraBox/releases',
    version: '2024.09.05',
    updated: '2026年9月5日',
    guide: {
      quickStart: '在路由器管理界面的插件中心安装，进入插件配置页面，添加订阅地址或节点信息，启用服务并配置运行模式（全局/绕过大陆）。',
      features: ['完全开源，代码透明可审计'],
      tips: ['遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版']
    }
  },
  {
    id: 'open-box',
    name: 'OpenBox',
    icon: 'OBX',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/39d94a842b499aa1f36467d01d4ec47d.webp',
    developer: 'OpenBox',
    platforms: ['linux'],
    core: 'sing-box',
    codeStatus: '开源',
    price: '免费',
    tags: ['sing-box', '开源', '免费', 'Linux'],
    description: 'Linux 桌面 sing-box 客户端，GTK 界面。',
    downloadUrl: 'https://github.com/OpenBox/OpenBox/releases',
    version: '1.3.0',
    updated: '2026年8月18日',
    guide: {
      quickStart: '下载安装应用，打开后添加配置或订阅链接，选择节点并启用代理模式即可开始使用。',
      features: ['支持最新协议（Reality/Hysteria2/TUIC）', '高性能通用代理平台', '完整的规则路由系统', '完全开源，代码透明可审计'],
      tips: ['支持最新的 Reality 协议，隐蔽性更强', '可以配置规则集实现精准分流', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版']
    }
  },
  {
    id: 'singcast',
    name: 'SingCast',
    icon: 'SGC',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/ea51843812c9a751995cd99d69ceacaf.webp',
    developer: 'SingCast',
    platforms: ['windows', 'mac', 'linux'],
    core: 'sing-box',
    codeStatus: '开源',
    price: '免费',
    tags: ['sing-box', '开源', '免费', '全平台'],
    description: '跨平台 sing-box 广播客户端，支持组播。',
    downloadUrl: 'https://github.com/SingCast/SingCast/releases',
    version: '1.2.1',
    updated: '2026年9月7日',
    guide: {
      quickStart: '从官方渠道下载安装后，打开应用点击「+」或「添加配置」，粘贴订阅链接或导入配置文件，选择节点后点击连接按钮启用代理。',
      features: ['支持最新协议（Reality/Hysteria2/TUIC）', '高性能通用代理平台', '完整的规则路由系统', '完全开源，代码透明可审计', '跨平台支持，配置可同步'],
      tips: ['支持最新的 Reality 协议，隐蔽性更强', '可以配置规则集实现精准分流', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', '首次使用需要在系统设置中允许添加 VPN 配置']
    }
  },
  {
    id: 'stelliberty',
    name: 'Stelliberty',
    icon: 'STL',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/806d164128540a2bbd29c9dcebb7d547.webp',
    developer: 'Stelliberty',
    platforms: ['ios'],
    core: '自研',
    codeStatus: '未公开',
    price: '付费',
    tags: ['自研', '未公开', '$5.99', 'iOS'],
    description: 'iOS 轻量级代理工具，界面优雅。',
    downloadUrl: 'https://apps.apple.com/app/stelliberty/id1612384759',
    version: '1.9.0',
    updated: '2026年8月28日',
    guide: {
      quickStart: '在 App Store 购买并下载应用，首次打开时点击「添加配置」，选择「订阅」或「扫描二维码」导入节点，然后在主界面选择节点并开启连接。',
      features: ['原生性能优化，运行稳定流畅', '完善的规则配置和策略管理', '支持多种代理协议'],
      tips: ['请通过官方渠道购买以获得持续更新和支持', '首次使用需要在系统设置中允许添加 VPN 配置']
    }
  },
  {
    id: 'streisand',
    name: 'Streisand',
    icon: 'STR',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/3f268c7fd8e1b0985540db82458ea35d.webp',
    developer: 'Streisand',
    platforms: ['ios', 'mac'],
    core: 'WireGuard',
    codeStatus: '开源',
    price: '免费',
    tags: ['WireGuard', '开源', '免费', 'iOS', 'Mac'],
    description: 'iOS/Mac WireGuard 客户端，一键部署。',
    downloadUrl: 'https://apps.apple.com/app/streisand/id1589481777',
    version: '2.2.0',
    updated: '2026年9月9日',
    guide: {
      quickStart: '从官方渠道下载安装后，打开应用点击「+」或「添加配置」，粘贴订阅链接或导入配置文件，选择节点后点击连接按钮启用代理。',
      features: ['完全开源，代码透明可审计'],
      tips: ['遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', '首次使用需要在系统设置中允许添加 VPN 配置']
    }
  },
  {
    id: 'surfing',
    name: 'Surfing',
    icon: 'SRF',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/64a782cd513391fbbf16f7dd88cf6bb4.webp',
    developer: 'Surfing',
    platforms: ['ios', 'mac'],
    core: '自研',
    codeStatus: '未公开',
    price: '付费',
    tags: ['自研', '未公开', '$3.99', 'iOS', 'Mac'],
    description: 'iOS/Mac 代理工具，冲浪专用。',
    downloadUrl: 'https://apps.apple.com/app/surfing/id1603821518',
    version: '1.7.5',
    updated: '2026年9月11日',
    guide: {
      quickStart: '在 App Store 购买并下载应用，首次打开时点击「添加配置」，选择「订阅」或「扫描二维码」导入节点，然后在主界面选择节点并开启连接。',
      features: ['原生性能优化，运行稳定流畅', '完善的规则配置和策略管理', '支持多种代理协议'],
      tips: ['请通过官方渠道购买以获得持续更新和支持', '首次使用需要在系统设置中允许添加 VPN 配置']
    }
  },
  {
    id: 'nextin',
    name: 'NextIn',
    icon: 'NXI',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/f6d4c43a8a6f5000a06951b2dce26ee5.webp',
    developer: 'NextIn',
    platforms: ['windows', 'mac'],
    core: 'Xray',
    codeStatus: '开源',
    price: '免费',
    tags: ['Xray', '开源', '免费', 'Win', 'Mac'],
    description: '下一代桌面代理客户端，现代化界面。',
    downloadUrl: 'https://github.com/NextIn/NextIn/releases',
    version: '1.6.0',
    updated: '2026年9月15日',
    guide: {
      quickStart: '从官方渠道下载安装后，打开应用点击「+」或「添加配置」，粘贴订阅链接或导入配置文件，选择节点后点击连接按钮启用代理。',
      features: ['支持 VMess/VLESS/Trojan 等多种协议', '灵活的路由规则配置', '多种传输方式（TCP/WebSocket/gRPC）', '完全开源，代码透明可审计'],
      tips: ['建议优先使用 WebSocket+TLS 传输以获得更好的稳定性', '可以配置多个服务器作为备用', '路由规则可以实现国内外分流', '遇到问题可在 GitHub 提交 Issue 获得社区支持', '应用完全免费，请从官方渠道下载避免使用修改版', '首次使用需要在系统设置中允许添加 VPN 配置']
    }
  },
  {
    id: 'nikki',
    name: 'Nikki',
    icon: 'NKI',
    logoUrl: 'https://img-s1.fastboostcdn.com/2026/09/22/8bf447ac2899177903946172c19045d9.webp',
    developer: 'Nikki',
    platforms: ['ios', 'mac'],
    core: '自研',
    codeStatus: '未公开',
    price: '付费',
    tags: ['自研', '未公开', '$4.99', 'iOS', 'Mac'],
    description: 'iOS/Mac 轻量级网络工具，简洁高效。',
    downloadUrl: 'https://apps.apple.com/app/nikki/id1619847235',
    version: '1.4.2',
    updated: '2026年9月3日',
    guide: {
      quickStart: '在 App Store 购买并下载应用，首次打开时点击「添加配置」，选择「订阅」或「扫描二维码」导入节点，然后在主界面选择节点并开启连接。',
      features: ['原生性能优化，运行稳定流畅', '完善的规则配置和策略管理', '支持多种代理协议'],
      tips: ['请通过官方渠道购买以获得持续更新和支持', '首次使用需要在系统设置中允许添加 VPN 配置']
    }
  }
];
